# ironic.yaml
apiVersion: ironic.metal3.io/v1alpha1
kind: Ironic
metadata:
  name: ironic
  namespace: baremetal-operator-system
spec:
  deployRamdisk:
    disableDownloader: false
  networking:
    dhcp:
      rangeBegin: "172.25.4.100"
      rangeEnd: "172.25.4.200"
      networkCIDR: "172.25.4.0/24"
      dnsAddress: "172.25.4.254"
      gatewayAddress: "172.25.4.254"
      hosts:
        - "6c:b3:11:73:ee:78,m600,172.25.4.60,1d"
        - "9c:c2:c4:29:74:bd,m601,172.25.4.61,1d"
        - "6c:b3:11:73:ea:a0,m602,172.25.4.62,1d"
        - "c4:07:78:d9:bf:97,m603,172.25.4.63,1d"
        - "6c:b3:11:73:f0:4c,m604,172.25.4.64,1d"
        - "b4:05:5d:ad:d3:fa,root,172.25.4.65,1d"
        - "B0:EC:DD:D1:97:F4,atlas800,172.25.4.66,1d"
        - "9C:C2:C4:55:E3:92,m700,172.25.4.70,1d"
        - "9C:C2:C4:56:8C:9C,m701,172.25.4.71,1d"
        - "9c:c2:c4:55:e3:3e,a700,172.25.4.72,1d"
        - "4c:bb:47:2a:65:78,nvidia-spark,172.25.4.73,1d"
        - "50:79:73:1F:53:AC,m800,172.25.4.80,1d"
      # we inject dnsmasq config here
      # https://github.com/imp/dnsmasq/blob/master/dnsmasq.conf.example
      # https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
      ignore:
        - |
          none
          dhcp-option=option:domain-search,clusters.zjusct.io
          domain=clusters.zjusct.io
          dhcp-option=option:classless-static-route,0.0.0.0/0,172.25.4.254,198.18.0.0/16,172.25.4.3
          dhcp-option=option:mtu,9000
          dhcp-option=option:ntp-server,10.202.18.18,10.10.66.32
    # ironic self maintained HA IP
    ipAddress: "172.25.4.2"
    ipAddressManager: "keepalived"
    interface: "br0"
  tls:
    certificateName: ironic-cert
