services:
  squid:
    image: harbor.clusters.zjusct.io/library/squid
    init: true
    entrypoint: ["sleep", "infinity"]
    environment:
      - DEBIANC_FRONTEND=noninteractive
    volumes:
      - .:/workspace
    working_dir: /workspace
