---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gzctf-postgresql-ha-pgpool
  namespace: dev-gzctf
spec:
  encryptedData:
    admin-password: AgBy9o8QBObPBs7wWQJJXxr2mCgLGSMomKqciXOis0dHHaUChtgnTJ5TcLpSXRaCDszqe6XYl7qbmD+ayr8K83N3SI4HrYSrNLs5UK5NAkacZ6ZApTALuHc3J8AE0ypbnhz1GEgNAe59W5GsFN78ZO1oBPOc45l6YuAvwR0dgyWS88T220fp0xqRH3snAQe2PwN/p6luOr7cVeHT1+m0wLryMAG8Lxhb1ozouFw7F92GvVsTZtBP2loIId/HM2OUHSsmW/7/HaA1YxjnwwSbGiwplr5aefDvfutxKEIHrc0OLaOrDk5ZAvR0nCyTOIKTJphJY96KRuB9iyMeNJnRHZyd9C4dFfPv4DojtRDA3Aoj2KneJMfFCI7d3PNADsenPOCMExT66lIHNHeYoUmuDnf3O9IeHwminNXDJzMCFl0NBH1oisZVsqvaI9uFdRxOscuqcfaONwYpos0bB7RFkfV+7nPFUrecLJCxNe2Hj0D0f2DBBjTCXxEpHka1JUGRB13zVwMpy6N46/KIeLH2a9M9hwaD37vVPf10j6MurdoeuqTTIcJUrYlX70ZnlTdq6hYCT9z551QO9s3fJrcZm3neIUtLXEbeDX5VnOY6L6K46L9+ssldEeDtzFcQupEHX/4FqbtkNRqhvUGsTDCZa67jV2wOkk3Hv5C+VU/PiczGv+BY9irCFa2uXsNETS6S1Ngmzhy5KNweOA8VFsQtH66guc3NeZ7pYN0=
  template:
    metadata:
      name: gzctf-postgresql-ha-pgpool
      namespace: dev-gzctf
