apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: litellm
  labels:
    app: litellm
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
  hostnames:
    - litellm.clusters.zjusct.io
    - litellm.s.zjusct.io
  rules:
    - backendRefs:
        - name: litellm
          port: 4000
