apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: litellm
  labels:
    app: litellm
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
  hostnames:
    - litellm.clusters.zjusct.io
    - litellm.s.zjusct.io
  rules:
    - backendRefs:
        - name: litellm
          port: 4000
      timeouts:
        request: 0s
        backendRequest: 0s
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: litellm-clusters-zju-edu-cn
  labels:
    app: litellm
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
  hostnames:
    - clusters.zju.edu.cn
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /litellm
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: litellm
          port: 4000
      timeouts:
        request: 0s
        backendRequest: 0s
