---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-masterkey
  namespace: litellm
spec:
  encryptedData:
    masterkey: AgCsMkWIjHJQqSWR3m8hMW6q+4YZ1jchgt8txZd3VHj1m3CG/Q95PYaxqMfQkz1qB8mIEUqAoDMMYq3knCdunpfcqgP3E7CMNRmxVwIkto4ZxZIjp1ws6pnlO0d1WGl3SADMTgg3jma5UfvwWeCrAIOM9y1K+gCxqCA/xI3sCNqXWolxaHDvsA0txab9Q5JPe9UZJo7EiFzc0b+RbhbNtuh5F/K+0VyyUAflHvJzXD6pRNPgN9qm5FidaqMd3G2niy0ZVfHumxWCAlRgfFoBPRA1XJ0LVk6/IglnU5B8HVvGaHB5l55/IzwKLZcH0CdWrpojiF/qg45RU3zmst4+k9mK+OWE9JaMeSXpuCw1pup5TvzUHqtU9CcS/qlFec1f5oFeUaBcd4Pq0wU0AIoSXQpoTaeQM1KEi/BCrUpU9dY8CvdQUzl2lsVofYuUI+ryO9psb97vzfXpEJXtoeaz0rZtiU1oQQfzLn2RkJIYmWxWmls6oxQcRdmZccB/CQd+UMtZK/i1t72S6UJVYUluyCB86eRn2Xq8yieIysSG8MH4ZJZ90Aj69wuVRyCtA8a7Psaz7dxFubt5DPJV0NImg+PvCT8p2CFI4BARf6FtO3QKnLdqSldrimhoi9uz1k74/hAS8KSM9Az9VHMhznuVbjpYkveQF9rc1NqTDr8n2RSOh9lq5DMKYRPAMg21dIzQlxMeiy/WUpy6tnVSjRlBWVte0g==
  template:
    metadata:
      name: litellm-masterkey
      namespace: litellm
    type: Opaque
