# kubectl create secret generic litellm-postgresql --namespace litellm --from-literal=password= --from-literal=postgres-password= --dry-run=client -o yaml | kubeseal -o yaml > sealedsecret-postgresql.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-postgresql
  namespace: litellm
spec:
  encryptedData:
    password: AgCQhA4AnAhP2HpITSur1kOuUGJCXcanKEs+XWSO0KDZARZvKGb6WA3GFI8RIzmAcGHdVXnP7uwFPoPvwCiqXx5nwUdvqImT5BpOopaLUtwcTByZUWSlptd8USRiEgAwX7vKUdjftjYwnH2Xxxzlru2ndKxWFkB0BjYiwKGlOK71PoKJR8reZ3FSWkjcwT0ESosjwOTdo2lW2moGURoGaayJzJrtrf7VE93vlq/kZL8hACuuJti8sI2zY+vX651nd3G5zuOW5U2LOz2QBKrgSdl87OWtdloyySyL1eHDQJy3B0PWzuSmmJTdUpA90J2V6plW5noKbu6oNRs56yNaXD2rYl7PM6iCySqp9tTLyeCwie01UBYx17myUZ2k8xe4rvzLcNRT+R2WNRyOTxD+iZQvkAEfFUI7lkuibCg0jKzUfVpPLSUGVxlaIeiyvQxPA1GNcUwTijhZkYhZLmcAcZZ5nwLUYc/5CAVsonAbJ5H3RW9ebNVNLBPYFYVniHIi7pzTPuR+PcFeSDfpXHiFdEwh8s/wJxxKvW1rJ+qiQR6+MN9TNi4WlcxJLOYgz3A9RX6CKkAEHgTuCppbMDOarAg6shMN00Tu3/qMf4OqNrJfmcbEMMM7Y8uknNXYXUHl2eu8DrLsI+7Sq08mDcsgze0qsmmhQmqVSo3NkTcohGKR93zrTvTXvvUjirpMw18YX0xzupK6tbJqmDvlq/t5cQ==
    postgres-password: AgBvxIlx75UEu0GCOTJ1DWJQivAtCzLuNiwlVdkgzfFSXGszf7ND4ZQZ8Tc4RJyeGqJjmjnCN4RIXjl0j2XD1CBtv1bU41QCPnf8t1tbQ9d6Hll0DYf+rh1TpwSido691CbrmFlyV7rdrzH/1TrC9sze+SGhYZq8zQYAkvIflVHJTpKtfdjipcpdmpZip4eP2yEjxII3VnWJot7OnY8tg9QMt4eOGH5ArgwNnjMCCWoaBn5xRdIS5FTIAml6N/7ofXaTozrrHpWxNHh6Nikf9hVOxWm3nQkyA0YCHCzqMn55EAHQqxLGCauLZOORViqY38LTo/XL0/cPwB10k2TVFImBQAQM7iVew8TeGsAVEMgDcTKWNwCmG3p2TQHmmgMfHJS/sIFCHjTROEQ8y0moflXjHFsa072rch4NAWbVUw7sXG+xdJo6BNT//nuUurHdawJ95wpEjbaRKIiqLZXo5Cp3sGLvO472NqgdG87K9n6oJv2ho04wI8OI+1GMH5bKF1VkgNRfZaWTkHwM0hrMy+Qrrzx8sG9ZYZ4d/SoWywwre0MKBlMf26CliuxyD2pMzch9o/RMgfo7bWeobEOiN60b0Ula8NwYWpws2zoMJe+RiJtpvk4KiYsx5pMSiv9p/Sl4ureAJQnkrq1n7al6LatemZM89VhoQ1fXEtjh3NFe4f8gkL0WLR8tRmtT0lcqZHHZlSOuFE2eE0VTAtxyYA==
  template:
    metadata:
      name: litellm-postgresql
      namespace: litellm
