# kubectl create secret generic litellm-masterkey --namespace litellm --from-literal=masterkey=sk-YOUR-KEY-HERE --dry-run=client -o yaml | kubeseal -o yaml > sealedsecret-masterkey.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-masterkey
  namespace: litellm
spec:
  encryptedData:
    masterkey: AgAqw9HIKRuLrhhirRHDFRB2Pye4emKJWGK2zlKmGmmoL0KueTQ0in6/XVlf83mzvAeieM6rssbL269Lw9bjcAUbMlep4gWvB84MhsWvjCnUD2XEHicopd7vpENb+zOlO4UXQfFtIjmBKcX4KcfZFUQYAnwmYtr0jIbRBBC/23+q6yDnk72iOQTeFDXv6h787ghT1x7duxsLsJ+fQES4PG4G9gYis1px3Y2nSrLloiQyz5zGabEFN7fUhqsK+/Tm8hTVLdekP8QYE0WAD4Sm95n4xaKdvwJwjtBBLRd7bMcPdk6VYr6ASGUiky4Xh5/hubsm4KxE0EneWpX8MPMhp8NY9q3zXiBNYo2/poxE6+hS5TkYL0Ij/qbTDsSfpb0h916KQ3jP5JMudGF4HU7CvmRtylBGsUpu+nrkl0SgoD8qbvpsjKD0I2UCba9HzheOL8Bclqgd3wH/Uy7/Y+QbKc7u6PZaku/zblOPZzWa/JBYyfD7HjgsY2YzyswcRd0kQzzc9dT8Ze4XtyFkbfmXRlkmOT/qiJRNcMRzyCMAokWfHYXaQ8Zl5+rxR71Y/Q1D3f/fS1ijfdJyxiJHTbKNX0ihllVFLSjA+N1yK4fcq6MHuo3MlQ/99jG+IF/+U+thGdd5LBYdtAWy6D1TAVZlGtxtLDi9F6WSY0LVXwX8noVXil7QpDcXgNHOXTGKL+vos6zUrI95hTxmEP40eC8HFHxf
  template:
    metadata:
      name: litellm-masterkey
      namespace: litellm
