# kubectl create secret generic litellm-api-keys --namespace litellm --from-literal=OPENAI_API_KEY=sk-xxx --from-literal=ANTHROPIC_API_KEY=sk-xxx --dry-run=client -o yaml | kubeseal -o yaml > sealedsecret-api-keys.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-api-keys
  namespace: litellm
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgCksy+YgZdte8FudiAEg3FRl6L1zSW0h6YP2yGyeOn7vtjmAcxvroU6wNoWHKq3hy2hTpwLER0i2Tw9S9uXsQ/xd8EXXgMcaKd4BNjKXkJ8INaq+yZ0YIlpuMghRrfmQjm9nHoW+WGIe14qMAxWCuSV+NHFJfI/V0knNu7KaYcHavI/CD7blsm3nVE39fJDQMT31l8i0O3jsmfS1eIDetbXf4l3Ij4ZgbEfdc/u8AxGRVVcjVNBZ2jsITlMKyPI14vSzzYqsdO+eGYevRdzwgtSl5qIpPjyB92+tzMnJ/KhGSkUEbN+vWddmpOxD1kIXab/5nuwDfrvzbmifdplFlJsnlk+TGUfgXKQzQ9BMMWtIcm0O5EUBVz/Yp+GBSoLEJ1D7vBcyqd/KZ6tMsksxLBBqItaZPuQ/e9nzWi5a+PozfBmGLHJRqXDm3VIFcgJCMXZfleLG5uaZ82CT5/xGLrRbK5nVgd99pdQfr/nMwJr20pHUrZISzza0E8nZsPQZ1mJabnFGyFwAMKhFSr8pCFvZgAISI2QdxYAAA6Mca/9rehJKG9CfhTbZzsFq63QvE2vlr1vgiDIMp02EvnF9LX5BkjF7w+y94IqrTBZ2FZWM/hzlswnzXK/UWkmfCc0Pa7T/I0w54JvEtdXHA1hOAZ8DKm3eQl56HiWhP7U0krjSqSE4Vf9C4AcY9EwxvfYfUGEiP5fpXQ=
    OPENAI_API_KEY: AgAUbEySKWDUYhGyKvL8NHbu4C4EFJXRXsYaYdFYHWrWPal8lIMROSOf6Z/xP/D2hRU9MP1VGHwKth7NGRpSvKThaTEFjrcqW5QlDdSmsGMuyu5Qd3Cr3gBtp4/INojIe6+wkC93Na1waGGVLcHa4bpLK6UMv7AJdGjbfVymvuadTLVv66X23ZBZL8PgYcYet4AjJWQTwcTobo9vfMUwQzL3wSeSTv6rsPK5brbGjzh7C+zlCMq9jvwH3Yx/JjR7KDOFm8Fj5AOLLZ2GkBJYeYfle6gO8V84zWcOtCcxOJmQuRrRO64nP8C6jew307H+15VqBXC4kBj7f8iIERKRW9DfeANSEx7TuMssNnH92s/rf8n7rpX6xslHVXhfIBuGjSlMfWyJedVRji/EHI+KOFpiJ8IRkhR76mSzD/PnSpgf81AaATa8gvjMYOcESHmxRptCtP3HqRKctKWfgHSFrhxAfa45GKwCR4xTJMw4SLkcW3VLoMSqD4OvNz4wYw8AyTSoHlfaj5DqrOPdCtnZG1ehBQP6sjJ9HQ2Hbf/c1WyQdkjAoJhDsYPvTX6VhSUoRFLRV/xnyswC67Jcj+WfKZoQbzKeNpxIEo1XZVvZBVSYjZdulQ+5tWRw8+yt9f2akzA6WeGukkzVNUe3e5nnwYiNMpNZZDTsWB4/Ye9MmobpoJXknXqryDcessOqZ35Jy/V9cBdujLU=
  template:
    metadata:
      name: litellm-api-keys
      namespace: litellm
