---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-redis
  namespace: litellm
spec:
  encryptedData:
    redis-password: AgAxk0IhsuTFww0RmVk1G/+1yAB86eQrVMRxxundqVxLOTPWaAU/JxkJBifl/Cye9bMzvYXjtInedtFlZrCwgaFoROpSIMEqwixkxmw+nRBoGYqXoWdP17QYa4Xcuv3hD1oanxyvLov18LWuJN7TTzNaNskd4LtTS1A1DKZ5EUkGZBQ22dqsWiTZP9t64L5yWuIdTV0orVYYZfkiWAp1/dgbDXEKVRAL3YXpuAN+11x8ty0UMYiY/CuFla0N/sjjWAuufdaNB/zNDlTMeH5/eLtegmSs05fqhseX3C6lbymD9RSFGAEfEewygBB16CubjFyXbd2PZ1GJ4/G23lsterQg+j2THIEou1s6cP+3Q8Wl2+rHuo2rOr828RgrDOv568NVWR6Tu5ctZG8irZjpfdNgj4WMwDkeddJj1Ah+bC7OV5GCzBJtoEVieAuwEh5Md5ktnvNfr+AZfNMK+mnU885f5GgKWFrvK+r8tC+gMG2L8raek3/5Y6Or+alOQwgR0TiES2MGT11nNdpWD6/u58NJtdB+iHWHIxGXU7V/S4HhUFHN8n6qYd8aK3tD5geAyqdvMM4qyvVDpDLZbMVZ77nDnuX2i++l8FSrquppMkDfv1GLqcryycF5wIIyGlyfJmoJu4LPAxD0PPOYU9Rx34UkQnz7bmMJhzO8HDOxmzhrEDlEZ1/msmAUKn118ecJ8niqvSoCUN8nex8RE3xCLPy0/bf3S46yx41oqXtJWls=
  template:
    metadata:
      name: litellm-redis
      namespace: litellm
