---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rfc2136-keys
  namespace: freeipa
spec:
  encryptedData:
    rfc2136-tsig-keyname: AgC944xMfmAFnHI3pBMb6kceCNvTI8GNYZ/Ytc5EAgHSx8n/WVQtuBIdBOrKnOTWx9k5OxznK21f3ybb8gqlG9zQirwQaLRMktDJfVcDzXFp+nwgKg2I5hu4ymqpE6n/Pg2cZKSkaJCe6oRHHirAKTu0XsYRH7fr+f4t8J0X8I+VhfKH/l1jTjQt8Ynyo0Lh8i9Trh5dOaLKAaPeKIJGC7IHyNhwS0erXrucY/0bhEgT3Wc1o6SARL2Kfyj8XRsLTgjvdUSk8dCT8Are0jZzTYuJBewD5ZzqjRUxx1Iww84cpTL4RPPVFjVbXyNTAnKe9WGZwIEQqx/bn6eB/yosyIWagAv6QxfftIPXw8UABBumnSOFnPGZkvl3OoWzSPj8g6vcAMWOCdgI4snadB3wjyASM0Y5mEvv4XSHiSuAYzlsszfCIg4JyFXew6O8xHnq7dtnmDerCYeZ6MWFDhcYzeaHxLcJ1ZaloCNNlWNcklTKxfjd889Vr4klQH0m+2pDp7YtURA6bEsW6ELnXATP7wy2jZAheMSp203y3BN7kBiWf6/SG4AYShmHoijsOPOYK3OBWi0TmKChPIilh6aAiJvlMVGn9HWRgztJpmtjVBLUjC5HdyLVskWziMqpY7g29Z5ftg6Q1OzXQPTnx4maCDCodEV4ARK7fXH7MfVXCJe724jSCc4TshrDIWHtXcenyqyGld9w12II8pMLBXSoYmXKmQ0n
    rfc2136-tsig-secret: AgBO5epSjIajmFrt93pLzYJedqgc9qn5cnqf1IIUa6P8GW8yQhr0JSHzdrv7upr+dqA1EbPgZ+56LiMawyLWCjKiZMAd8G30ds3NdlpknnBICmq7cTlCTmhI1Aq22RtPE6jB9uHB7P88vs2JTqnsy6DBSdVuv4zO6bsQ3MED/1VTK4VI6i3jthDHnx7344FwA8+l5SmRu2nc3enxXH0+Fd+MmkvYK+v0jcaJm+VV70ePRZX34Qw3a0a7hj7gI+kQ6tUZU3bMpBRWjZgeVr+OPnQ2/B+1LjYtIAgzFtwvVMAhTd3PGZqFDAzsS4x8fSQ4p9AI5N7q1XZGbApV2hThmpBzIPhLlxYZUchsfyAZswdYbDnp3TfE7yyhXhWJHikOMoWk6hmRBrFbKc9aCPCXVkuae/i22fd7z4rwMTzSzQkscaXPt0bnvNeBcEBms0mLVmaEYrVQ5+rSBlU1dElN3Evgw7VPAf4TbvJUFQGeWq2p4mB8SKrIikRZDjV+dBqF9fuibXsFIagyp/i3c3W7dcVA9Ubco5JmrtkQrdZ3cskRmRnmGe2vzH7p/mzdDz+zzOEZ7nSfQ1hWXJiE/pp0Y2vSmhEYPB1E7BvakggsrwyEq1kyoxet6Om8V0LW3NHj4u9hSFobjzxyDSojiGfzZRx1uIjQnmJxLWfRB5NULehXokofivV3/S35t9gPLJ0A5gN3BvqnqRqhCwXb+iy3FgJeA6Xl0jAqOq3JaNMbjJr4adcIwhPG82vDdCamIZKA2tsvDhZMXGnwr+PfA47ysYo/SX5bs/zZ/NoDOqEFutyTbf7PZMnbhjYe
  template:
    metadata:
      name: rfc2136-keys
      namespace: freeipa
    type: Opaque
