apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tekton-dashboard
  labels:
    app: tekton-dashboard
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
  hostnames:
    - tekton.clusters.zjusct.io
    - tekton.s.zjusct.io
  rules:
    - backendRefs:
        - name: tekton-dashboard
          port: 9097
