# ObjectBucketClaim for storing Packer-built VM images in Rook Ceph RGW.
# The provisioner automatically creates a Secret and ConfigMap named "packer-images"
# in the tekton namespace with S3 credentials and endpoint info:
#   ConfigMap: BUCKET_HOST, BUCKET_PORT, BUCKET_NAME
#   Secret:    AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: packer-images
  namespace: tekton
spec:
  bucketName: packer-images
  storageClassName: ceph-bucket
  additionalConfig:
    bucketPolicy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": [
                      "s3:GetObject",
                      "s3:ListBucket",
                      "s3:GetBucketLocation"
                  ],
                  "Resource": [
                      "arn:aws:s3:::packer-images",
                      "arn:aws:s3:::packer-images/*"
                  ]
              }
          ]
      }
