---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-credentials
  namespace: tekton
spec:
  encryptedData:
    .dockerconfigjson: AgAlb/pKYRinK7J6GuDe6f4J5mka30fxfzUb+RNCYKZbj5OhtU4NbdL2xqiCAbsSPXbYJLqylIwnL7FIRkmcV2OaUPtgRNoo3wahsJtd12qaiidDHaLvUcCNEUOuL4MGF3wuaVmmo3wjiR4q7/2zAmIKYD1rsxZG/GT0LRbRYhLQxNwXjMGhnKKRdCogOeU2gBxU+E5vfsjcO1ZV9QlSadfZSs1JFFAac2L9/x9XMWAOfaDvF22//ag85UPfvMZlRT3inx9DpCYLy5abQ5nu4wJ6gqn9rNHQAPDFOudcoy5BJlO6lijkPa5SbxjWalWFsyZm1vDW6fwyw14FOUg5huiVPcX/BKV3GzSv+OSsS2Y4tP/jXdxU/sUiOdlnY78dDIQzaZwbxh67O/aqKdv90Aemf6nLa70pFjMACyC8r3dqS50nA6XePv9vumK+wr668M+f2oFZ09T+Niqbzjyhc29GYVkAPKfjg4/yqO33FIrbAXw1/hm2arCpmt2NH+gT4gR8Sirh3XTDRe4cJ+08ZG+hW020KwtmBWD9q8x6oOc3hrb/DDOK2AquHGLG8155IehiSGulbrh4LlTnht8p7PLsZAr8BPev2QadqwzqjPHT3lUrZIpEzoFdXTpOxHy7eM5cixoVaxa6MhRWwUSYBkDq+G5ajqKokwddvbRBqsgDIJKJPvvYeFs/t8vmjkgqUgusZ8uu/hkeZ45vHkqysT8sHrtfveDyCkcacr5VZNzcckjPwYOq4bokf+/fE/KUvVY2SpLBjeododYe2ojUvrzweOVm8PDQ9IXDe3TkFKfEzm7jWsGCLW73YD1v/LJFg+X4mLX2xvDMp1OJwAiZV8SUf/uTJeREo6t0eUWPBr3pWxUjxFcdAu2S/0EeNKWUTImpa38ebQRTVRO7t12UEKPuy83d83K9/TmPrzjcAu4ivdrh6+eL56GNf0JkcLbqur+kqAGTjD7avV95Dx1f/VR7ZQk9FF5xGJgy3WCzar1NJ7RS4Y3x7KmdXhY69IyH87m9ROGq8Mu3lvluXpuIOO/dmwjumSUv/j26yLh0WUyDZHkUZzWK5QfnwjObIV5eUA7tEI9dsOA4h2YH7OZ/rHuYNjXGGRtDbzwtx8e1NbwIYVTnRvu3QsrQmPLtuGQ+BBa7uTOVDwLJHJw0ZRq/mzPWmQBrNjMYUjVcaClRKaERckgEIw4vgV1Xof0UhaaTV9YJwjZCIX1JSVatbFsJoadppsFBrudNt51w7GMJmS1G4SnqEgdp8g7w4hJaiMMFOaem0Dyf6xlHEERMhwD9eQ==
  template:
    metadata:
      name: harbor-credentials
      namespace: tekton
    type: Opaque
