---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-credentials
  namespace: tekton
spec:
  encryptedData:
    .dockerconfigjson: AgBdBU+9cYyaHvYaE5P1jge0hG3AlvM4cqN15efel+42IPDHNzekXSoJSavcg4ms41MFg05am8HMwq0Li/AoLzEGlc0D3GGek/rMXFTY/vdVeWlD4VXS5PDUBJovbcSY5UWLTtWMckUXev4ch2aN5HZbkqOwf+ryITuYvGpqX9Zo+goxZNT2+bhIDktyud0IwjYy+ymd2O5nD5xUH6Lpqc70P8Xms5HCKNtPG663rdS3alr9/YxxsSx/xvSfNfoFlu5rqG/JvWsvXks5Stvzl5hh4Ck4Ioesn8sqltD9LIHUuYI1o7Gf1FkCXjz5C1JXcah1+/Bx3JK4dcZgrpYjxv+Kw3cXsbFQZDeHeYnD2nP4fQZiUJAo7ZXVjlcwakdLk4xI2ASUaoulEbB4pBVD0HQEphkpPCM/Sh38gyXeMTgAY0Rvp9+9gOEUNBvaW7X9u3N/tIx0jpdET/68BC7JTRupR1T2gGB7yt+jph1oqp6vkOYY6qrO6tEK03nURA15DvBMoQDFbQh510mIYGaWHTCrSffKP2Gy9VQazrTFM7rLrGYbzoSvrtylUhx3gSRp51uYJFatkPOdXI3/7XLzcwlcRZ/QOy+Gl+lH4JBylPX2bvZpLada7wdv1QxgRD/P6s4Ppiisj6TeNRWC4+0SUSEWDgoBCoYjjDWGZ3pCWWy76umGyHjl4OzrPzdkSvNH3hzZ/cFYGvFrwR5jcX43qM9LgyGdrghZ0CFmCZl41cuIN2CCmZ7Ft6eLDnb2YzNdQ3W6woeCDXnT8G8g1w2mngBT+mykqX/Yroiys2L5XAMY2xxX3V2FUDmybzKh0LpH9pB2s79GhXB4EYRWDw3/pvPU2uOpEX8ZpbJYKzN4mFKTc/0a3CqQjASwQXogiKBHLgo8wifJoA7SNj6ky4MfCtuLWHeHzCYZYOJd5LFB4s3SWgaRN/vbCWtsX8cUiexha9RrYaVwrd5Zir89wcCev1qTsTRREuIyyWZyI5Z+E/6QmYs6r49iEC9JMr3PExZHoQ==
  template:
    metadata:
      name: harbor-credentials
      namespace: tekton
    type: Opaque
