---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-credentials
  namespace: tekton
spec:
  encryptedData:
    .dockerconfigjson: AgC2hez+2oIOdtxTGsGCw/VUXuPMAnlDWgvFofReb274gt4C/TGZPFTNSEMRLjJvFLXtNxw//JteZ7XXGGbsjOZQZIS5MuucQj1zVq6kUf9CNvF/FBVHXe+qzshjnqfkoEHS/uYVg6RzWsRKMhDyuSDiLDi/Pg+aOQ8EReZJl6yuL4Vy3zdCt8+88hXLAoxx7u0qMsKFzGufH7ZCL6j7X8DHXrUg9U55oG71b+l/uMoFRXochewz7cIPJHqbk7uP8z30LF7qxqRBlhDolr9rb9vP5BFEbLSwSqzTUeaxfr22Oyd93jX851LtFaJk0c12JVyrhptk1bfNxdVBzmN+7qb/qAStMaLWJOSumAz1fRBb4Uet+kugsK4v7wFejliZYg7M/x1iPNgLx2JfxqODUBZzOHuZqa7PIIB7vrYJ6TYPUliZyg2Fg+/I0ZjHXYXfjvdRe4B7fdodQLYgnEJZOVEevttBsaYCfvAnxb3Hb4NX9eiAQMNddq75oTx3efL3akyGOUnnOapVn6pz8sMorVWtIlBgGKaxiLF5S5T11OQD2Adp8fj9Cg+qsmksU/CMKaMzqrsYVeaHJ7QY/DG9eA96dH9FVIGeNfWEsLXVcooHLykI5scV7d4i96LyLJpN4L1GqygWc2oghku/VKMhsmC01Xfo7fzGYIsmKEwu5jq2fnxpMrWXs8yuDzPn24ydpjVATVo++Ii31c3MBqx1WquArbueD9qamo9N2MAabZUvOt/UNkoTXCP/uNHhwL3oPW4EAarDJbMJtMmo7QO1mrafU8xvBgO+E1Wv7fwZUSkcTYUpEE76gRJbB1KdnBZMca0dHdHAoQEFwHA2rUlJV74K+OAaHWMul8LYVrZRzmsZkLJ97I+qSXtHnm+UXkW6i+Qr1tbV7C3DBbWolqLqkqGG9nvJFyEA1aJywEOaZam8PTpaciZnw/4enBteE8cv5VFVXBpi5hmGwQIsdLdXEc1gyiO4FMCNHpzIzRnGuhEbOranhdHdX1GP87mfVsBPxlNhMw90cjYHoIJEPAVL
  template:
    metadata:
      name: harbor-credentials
      namespace: tekton
