# https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-secret-yaml/
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argo-cd
spec:
  encryptedData:
    admin.password: AgBKgzLCycApLkCj5qM8X40GA3Iy7CZj29ym87rvDK2/i5z81Dlo/MNqPi/T3usvD1a1EYa3s3albcEc0pJ2nUxKO3xRJByy4/OWOhrEmKMHrxuiET9Yr1bwa2bBAJLKXSVlvIgFjak6fWaE8MKvXqtYV/tNozUPdYGWm3eh+u1Rxv+qEM1Z4n/04FtsP8RIj9878C7RaXW9Dj+F6qvtgdI1oVFAjOgo1PoaJyn/JvJ7net0HkfK+gwzSohMhoy6HT/ANDXEeT5qB/C2YjY3PqWWd9d6RZZJirtDUetZ8z8KyAxIrzT32fDzTnH+F8u7Oqra1ybVVgUa4DqFJByVMrc7WgC23BUxEbgZukfjribHCG6OJEe6SDtwCH23AjBgi21nxa+8Y48lOzgAdN4MlXQVrfXaQz52OpUj2vND7EtXUDU8mkLqo9gjC7nhuJp3owMGgp9UDK1mcKLxh34ozaizdK+d3kNPN/5Gc5nJ4sbFu+CAXjVY1lWnadItlmtRjBecUYQ4idnKDJMBxuQSXiA3I9iweAYLSG6RHmTPLNpUImuUMwTCU/spVdwXWQfIn/VT/JupYQetQ0F0kjF3/F5gSyjgYaA7lyUhGPUvq13jIzVe8ntlS47KJqkIIdy/j09IoziezbUg9ZZoSQnRRkc0Par1LMiLEC5shcYYYT9lH820nT4HAu0mFBGnFWPTEa4eDyWTbWjOgobivunNWCAmtXlyxclOE5NjCCx5jGhCZHD9ilX/u2ePd8pw9uaocCTsCpJW9Jc5+iE5ZYI=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
    type: Opaque
