apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: buildkit-ubuntu-run-
  namespace: tekton
spec:
  pipelineRef:
    name: buildkit-ubuntu

  params:
  - name: image-reference
    value: harbor.clusters.zjusct.io/library/ubuntu:latest

  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  - name: docker-credentials
    secret:
      secretName: harbor-credentials
