apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: buildkit-mihomo-run-
  namespace: tekton
spec:
  pipelineRef:
    name: buildkit
  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 65532
  params:
    - name: git-url
      value: "https://github.com/ZJUSCT/mihomo.git"
    - name: git-revision
      value: "zjusct"
    - name: image-reference
      value: "harbor.clusters.zjusct.io/library/mihomo:latest"
    - name: dockerfile-path
      value: "Dockerfile.zjusct"
    - name: context-dir
      value: "."
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: harbor-credentials
