apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: packer-run-ubuntu-
  namespace: tekton
spec:
  pipelineRef:
    name: packer
  params:
  - name: git-url
    value: "https://git.zju.edu.cn/zjusct/ops/argo-cd.clusters.zjusct.io.git"
  - name: git-revision
    value: "master"
  - name: packer-file
    value: "packer/ubuntu-simple.pkr.hcl"
  - name: packer-image
    value: "harbor.clusters.zjusct.io/library/packer:latest"
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
