apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generatename: packer-ubuntu-run
  namespace: tekton
spec:
  pipelineRef:
    name: packer-ubuntu
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
