apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: packer-
  namespace: tekton
spec:
  pipelineRef:
    name: packer
  params:
    - name: git-url
      value: "https://github.com/ZJUSCT/argo-cd.clusters.zjusct.io.git"
    - name: git-revision
      value: "master"
    - name: build-script
      value: "packer/pipeline.sh"
    - name: build-image
      value: "harbor.clusters.zjusct.io/library/packer:latest"
    - name: upload-image
      value: "harbor.clusters.zjusct.io/docker.io/minio/mc:latest"
    - name: upload-s3-prefix
      value: "debian/"
  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 65532
  workspaces:
    - name: shared-data
      emptyDir: {}
    - name: bucket-config
      configMap:
        name: packer-images
    - name: credentials
      secret:
        secretName: packer-images
