apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: packer-
  namespace: tekton
spec:
  pipelineRef:
    name: packer
  taskRunTemplate:
    podTemplate:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
        cpu-feature.node.kubevirt.io/vmx: "true"
      securityContext:
        fsGroup: 65532
  params:
    - name: git-url
      value: "https://github.com/ZJUSCT/argo-cd.clusters.zjusct.io.git"
    - name: git-revision
      value: "master"
    - name: target
      value: "k8s"
    - name: build-image
      value: "harbor.clusters.zjusct.io/ghcr.io/zjusct/argo-cd.clusters.zjusct.io:latest"
    - name: git-image
      value: "harbor.clusters.zjusct.io/docker.io/alpine/git:latest"
    - name: mc-image
      value: "harbor.clusters.zjusct.io/docker.io/minio/mc:latest"
    - name: cache-prefix
      value: "cache/base/"
    - name: upload-prefix
      value: "built/"
    - name: public-base-url
      value: "https://radosgw.clusters.zjusct.io/packer-images"
