apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: packer-ubuntu-run-
  namespace: tekton
spec:
  pipelineRef:
    name: packer-ubuntu
  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 65532
  params:
    - name: git-url
      value: "https://git.zju.edu.cn/zjusct/ops/argo-cd.clusters.zjusct.io.git"
    - name: git-revision
      value: "master"
    - name: script
      value: "packer/ubuntu/run-packer.sh"
    - name: image
      value: "harbor.clusters.zjusct.io/library/packer:latest"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
