apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: dev-openclaw
  labels:
    app: openclaw
data:
  openclaw.json: |
    {
      "gateway": {
        "port": 18789,
        "mode": "local",
        "auth": {
          "mode": "token",
          "token": "${OPENCLAW_GATEWAY_TOKEN}"
        },
        // "trustedProxies": ["10.0.0.1"], // 只有当 auth.mode 设为 trusted-proxy 时才会生效
        "controlUi": {
          "enabled": true,
          // "allowInsecureAuth": true, // 仅对 localhost 有效
          "dangerouslyDisableDeviceAuth": true,
          "allowedOrigins": [
            "https://openclaw.clusters.zjusct.io",
            "https://openclaw.s.zjusct.io"
          ],
        },
        "reload": {
          "mode": "off"
        },
        "commands": {
          "restart": false
        }
      },
      "browser": {
        "enabled": true,
        "defaultProfile": "default",
        "profiles": {
          "default": {
            "cdpUrl": "http://localhost:9222",
            "color": "#4285F4"
          }
        }
      },
      "models": {
        "providers": {
          "litellm": {
            "baseUrl": "https://litellm.clusters.zjusct.io/v1",
            "apiKey": "${LITELLM_API_KEY}",
            "api": "openai-completions",
            "models": [
              {
                  "id": "plan/volcengine/ark-code-latest/openai",
                  "name": "plan/volcengine/ark-code-latest/openai"
              },
              {
                  "id": "plan/volcengine/doubao-seed-2.0-code/openai",
                  "name": "plan/volcengine/doubao-seed-2.0-code/openai"
              },
              {
                  "id": "plan/volcengine/doubao-seed-code/openai",
                  "name": "plan/volcengine/doubao-seed-code/openai"
              },
              {
                  "id": "plan/volcengine/glm-4.7/openai",
                  "name": "plan/volcengine/glm-4.7/openai"
              },
              {
                  "id": "plan/volcengine/kimi-k2-thinking/openai",
                  "name": "plan/volcengine/kimi-k2-thinking/openai"
              },
              {
                  "id": "plan/volcengine/kimi-k2.5/openai",
                  "name": "plan/volcengine/kimi-k2.5/openai"
              },
              {
                  "id": "plan/minimax/MiniMax-M2.5-highspeed/openai",
                  "name": "plan/minimax/MiniMax-M2.5-highspeed/openai"
              },
              {
                  "id": "plan/bailian/qwen3.5-plus/openai",
                  "name": "plan/bailian/qwen3.5-plus/openai"
              },
              {
                  "id": "plan/bailian/kimi-k2.5/openai",
                  "name": "plan/bailian/kimi-k2.5/openai"
              },
              {
                  "id": "plan/bailian/glm-5/openai",
                  "name": "plan/bailian/glm-5/openai"
              },
              {
                  "id": "plan/bailian/MiniMax-M2.5/openai",
                  "name": "plan/bailian/MiniMax-M2.5/openai"
              },
              {
                  "id": "plan/bailian/qwen3-max-2026-01-23/openai",
                  "name": "plan/bailian/qwen3-max-2026-01-23/openai"
              },
              {
                  "id": "plan/bailian/qwen3-coder-next/openai",
                  "name": "plan/bailian/qwen3-coder-next/openai"
              },
              {
                  "id": "plan/bailian/qwen3-coder-plus/openai",
                  "name": "plan/bailian/qwen3-coder-plus/openai"
              },
              {
                  "id": "plan/bailian/glm-4.7/openai",
                  "name": "plan/bailian/glm-4.7/openai"
              }
            ]
          }
        }
      },
      "agents": {
        "defaults": {
          "workspace": "/home/node/.openclaw/workspace",
          "model": {
            "primary": "litellm/plan/volcengine/ark-code-latest/openai",
            "fallbacks": [
              "litellm/plan/minimax/MiniMax-M2.5-highspeed/openai",
            ]
          },
          "userTimezone": "Asia/Shanghai",
          "timeoutSeconds": 600,
          "maxConcurrent": 1
        },
        "list": [
          {
            "id": "main",
            "default": true,
            "identity": {
              "name": "OpenClaw",
              "emoji": "🦞"
            }
          }
        ]
      },
      "session": {
        "scope": "per-sender",
        "store": "/home/node/.openclaw/sessions",
        "reset": {
          "mode": "idle",
          "idleMinutes": 60
        }
      },
      "logging": {
        "level": "debug",
        "consoleLevel": "debug",
        "consoleStyle": "compact",
        "redactSensitive": "tools"
      },
      "tools": {
        "profile": "full",
        "web": {
          "search": {
            "enabled": false
          },
          "fetch": {
            "enabled": true
          }
        }
      },
      "plugins": {
        "enabled": true,
        "allow": [
          // "dingtalk",
          "qqbot"
        ]
      },
      "channels": {
        "qqbot": {
          "enabled": true,
          "appId": "${QQBOT_APP_ID}",
          "clientSecret": "${QQBOT_APP_SECRET}"
        },
        // "dingtalk": {
        //   "enabled": true,
        //   "clientId": "dingxxxxxx",
        //   "clientSecret": "your-app-secret",
        //   "robotCode": "dingxxxxxx",
        //   "corpId": "dingxxxxxx",
        //   "agentId": "123456789",
        //   "dmPolicy": "open",
        //   "groupPolicy": "open",
        //   "debug": false,
        //   "messageType": "markdown"
        // }
      }
    }
