# Debian
- name: debian-13-amd64
  arch: x86_64
  iso_url: https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/debian-13-generic-amd64.qcow2
  iso_checksum: file:https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/SHA512SUMS
  modules:
    - 50-test
- name: debian-13-arm64
  arch: arm64
  iso_url: https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/debian-13-generic-arm64.qcow2
  iso_checksum: file:https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/SHA512SUMS
- name: debian-13-riscv64
  arch: riscv64
  iso_url: https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/debian-13-generic-riscv64.qcow2
  iso_checksum: file:https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/SHA512SUMS
# Ubuntu
- name: ubuntu-20.04-amd64-ascend
  arch: x86_64
  iso_url: https://mirrors.cernet.edu.cn/ubuntu-cloud-images/focal/current/focal-server-cloudimg-amd64.img
  iso_checksum: file:https://mirrors.cernet.edu.cn/ubuntu-cloud-images/focal/current/SHA256SUMS
  modules:
    - 50-test
# Fedora
- name: fedora-43-amd64
  arch: amd64
  iso_url: https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/43/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2
  iso_checksum: file:https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/43/Cloud/x86_64/images/Fedora-Cloud-43-1.6-x86_64-CHECKSUM
# Arch Linux
- name: archlinux-amd64
  arch: amd64
  iso_url: https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
  iso_checksum: file:https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2.SHA256
