---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: dev-observability
spec:
  encryptedData:
    admin-password: AgAiu6s0zD9nUvQMiVwk3A0RzIH7h4aEF/fnOnsrhL5kKt/EzB0T+Lzl9juSDeOo2/AFDfmJqsF3JDNZsqmrINZVIxQOB9SHf0JAAxyNsCYp4rh5mMYE48OIJPE++jcn2MVVQZ5ADGjSPoJHiMvUrsk0h9SoLB5+Opm48wlTJe27y1uDVsEe955R/1oUhEpm6qhdrgux3Zli/AFGJ85LML3jU7PZCTxK+HiUP7uZI6XOjQdKqe9x7YwaQLUkpzRjzhKMl0TnhE9XTED8DA0T4qMZxLmRdlvo5Z3f2t7e/uO2mTW4dJ2ZXrXJ1NH5h2FfgzEdEBb2c9Tbekcgz4ZY+naXPUGxxJqnyQp2P/VbpvNpdz35+tIYdE0vsg/FZHVzhGTadR8g0bnhFpA9QkeWQs4aIq9V9YrEE+baVQauJFib7qGJkI09W/h7PJKBoWbREG99mjdmxZ97PV2zq5R69qFXAa7yOnsxEbaq1grtGMMltGCEt5OepZilhEVbpE7P/qtozgLmiXtUCKJBu643B7TmQQGWxCp4pMudKFZ8hstCOKZaZMfGcn6obkEm965Tn5rb+qJG3N6RwSWBkD4n72qxgO4fidBu1PZ5WqyvRcdYW0IgrYeu+u0ek6NUB3EmMqDpZh8GCn1gOFiTKgcwue3/zRQe/B1tTENxOAG9gahziNJ29T1DPu4xyC11tWS3xIxUwzwxj4bRjfVtQ+PkTw==
    admin-user: AgC87dtfnQMcat3HqOoM7I6XIVcdtZcnRnewclAuL4SdKIP5FjEaPAofkN5WFhoKShKSshTuxzweQq49/RW3+NstBa2BO9M0qiCaSaDsJG3e94DFtxoGipaVgBUl2IV4fR6klLwU5DtoWeV15UBh09gOPKyg0tiN5zEqniYiNOLr0NwfXDjSpgWBsyE2PQGgMXgUYdQkKxuSenKk4jrC3+3LFdY4N2K+Yh7rVyElEZt2KG/5xL2szKnSqcIzsnm3H/gJhlEoTq7x0rdq4DWz+98kWs96F90uzCTpq60STLpYtiOrVxHomqSKRfLRNWEL6ExG27l2YgU0iTmxP/6idvpPqjqtNdOvGiJw5oGAhv0OBS0bXQvxE2rsS9TMkNJZqSlf88o9eqJgtudS58psxVqBBNlsead+aBh14yxgCaSkcKUio1ixYXCOSEk9ZuBnube4yfkwLIr4HNjnbBl9r5uvfM9+QZ0rwCPPNQZXY5vi5YSBBXMHwwQcZP+FeduSarHfqcNX4EMuXvqVhbkGnaBFuuEv0FXBsnguTKZCXRB3iOVIhWXFhChPhBY1eP+mgGuhgJn3WxBDBlVH/ghCMUGpX8AAlpuNZ96veaTmAEgAMNndHfh3/L/eKVvsvix8FQUfUX1LXhJ9zrQC/n8nYPiOsVJj2qFd3mr+QEFxXEGChqGODNrt5CXIPVFH+ot0qYVfXh3QWg==
  template:
    metadata:
      name: grafana-secrets
      namespace: dev-observability
    type: Opaque
