apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-tekton
resources:
  - https://infra.tekton.dev/tekton-releases/operator/latest/release.yaml
  - resources/00-tekton-config.yaml
  - resources/01-buildkit-certificates.yaml
  - resources/sealedsecret-harbor.yaml
  - resources/02-buildkit-daemon.yaml
  - resources/03-task-buildkit.yaml
  - resources/04-task-git-clone.yaml
  - resources/05-pipeline-build-ubuntu.yaml
patches:
  # https://github.com/tektoncd/operator/blob/main/docs/AirGapImageConfiguration.md
  - target:
      kind: Deployment
      name: tekton-operator
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TEKTON_REGISTRY_OVERRIDE
          value: harbor.clusters.zjusct.io/ghcr.io/tektoncd
# Normalize DockerHub images by adding docker.io registry
images:
  - name: moby/buildkit
    newName: docker.io/moby/buildkit
transformers:
  - ../../image-prefix.yaml
