---
# PipelineRun to test the Ubuntu image build with internal registry
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-ubuntu-run-
  namespace: dev-tekton
spec:
  pipelineRef:
    name: build-ubuntu-image

  params:
  - name: image-reference
    value: harbor-core.default.svc.cluster.local:80/library/ubuntu-curl:latest

  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  - name: docker-credentials
    secret:
      secretName: harbor-credentials
