---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-credentials
  namespace: dev-tekton
spec:
  encryptedData:
    .dockerconfigjson: AgC7WTPZEnWDNWllGqc9TExk+duTcoCpm/wn0nInwLbaIHXrWoDNJtqQccaSmvvg471jzM05xhfuRp3cy6H+4fB7rKFzrU1YA9VOYePMcHooELIigo3z3vKIOTtfS+ChRitmYnNzi34BsOgr4BBZLDn5AuA0MwfWFKo8pPEeUxvja9ndM9eswT0CwnVccpWKmpiDIOny/nC5L7h8p/TBezGBECsjNzngMdxYr//GS4XvDgaGUjJd72/jUpYbaSwMpbd96+NgNrmX7I/3qZQjRwBw1FDcp+SuWScuycB+skinKdWO1h/42NDe//TF5DOXaBzMaj4ovZ6K2w2HQ4fCbIJrDtNhWxe5vrWYOGKtbahl6Fx9fxoal/fq7JBsOJ0ANExzGqIPLUn8wSg+OYu6zSmyiUilQLd1M6eGWlcnRNWkctU9LqVdTUmpu4fN5ZsR/vnVpv8Pl8Q1q9QD0OnhVH/mhqKRC4GdJpTVKS/PTDFhas4BWNU3ElYYxJPIwdNZ69v/XzblbMN4ixzlLxmJEbSXWicCCy8WMd/R6ysboaf77o7gYl2bWTKe5RglvCIiBiZf3/zvKtqaDvT/KBFFafISISlslCDkx/RibSh2upq11HPSHbrplCtKAG9HbXKFm4PdWbyf3oJrpYB3+46dEddr4GeycbdgGDgQUfJXvE1a34TGKZNziTnoJLEhVhfaOtFd1++eU0nQhUlgms5Mu15DJXKMZgWPbRs68+7Q1+ylGs6H/zqzMGhMIoBwdq877WV0WHZdrCQogHXBLw3Ny8mRlizVrXvbmLUatAstYDZyoFvna1/MSiP7tfkKoh5dX1H5dBxWZ/f3pbqKYAqFTpKyO+aDvv5Xxn1+Db3RfeU1B96ErSVFHyi95DNkndfaLsSy89LEThNjk9LPl9pNZ6GgQTzm8FYyQm6BcjAivu9EY9qJXAmJnDU=
  template:
    metadata:
      name: harbor-credentials
      namespace: dev-tekton
    type: kubernetes.io/dockerconfigjson
