---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gzctf-secret
  namespace: dev-gzctf
spec:
  encryptedData:
    admin-password: AgB/1FLnJfNcw4exOZ9C8lE6DsN0FnWFxHbTT9sXnJdKtkk1H+cUfQ6chqzwI5JFnL7nQpvWfUL10bSnTAVw3Srxx/gaG8QHTfP5HxnEydPscdo1kxxPabnkvE2aeRBLOy5Cw8+0hykeUGbqhQWrQ0xOuW1ieNfS6V9eqeJR3uz/mqSPCFlBlXys+BjPenqWeRL5Sa8yq+s6WhMBZYI1Acic3p2cFkhmIOSeFmIlf/ECyxcXp7pdhlMhGeGpfvMz4sHSEcade8pbijuJgteBTBCOhRxfcr8I9EXTKgXvmQ53D9gYkBJJJRZ3I6NZSWuoJsXOQ5G2YPdACitQNU3iKbtq36CtYDaRW6AK4FIQyoq9daeKPDoczdWUjtZ2nShi/aIaAt+aMgzgztgtqBxhsGQWbXGe9QwpsNvGQeBY6NgWxXuXYArgYNhy5Nt4X3ZKe2psqBQRwhDevjdSwrJ8ObEhDh1Im4qb8m03xdODE8WLKB1ZzV5JMtBg6T0VNZjoHH3SttsMZjQ+qXK5oj54qXquW3q933XWKZQbgt+hRcTb1HzGKHS+6dgxvXZ0ymo+JhY4KgAQWSVUJVIZFn+gFzhZ61wR6SFW4IEbJd9KUnfGo1Lwxy6uDAq70kA1hTlbIlCuJrTXE+wPgowthaT0Rl49MMKz4iDrtzVgxvBSLubcYQNuU95qxJuPEhIN2IOaSB1wMF4xWG7C13uAxfOGIKjrzjb2SZBmX9B0MX+4rjrI8w==
  template:
    metadata:
      name: gzctf-secret
      namespace: dev-gzctf
