---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-credentials
  namespace: dev-tekton
spec:
  encryptedData:
    .dockerconfigjson: AgAWAKZK4zyZzhCO7WCF8KMw6RHfFYZpY+9/MNzrPx9GZ4AO3ERMqWoLRGXKBynl5be04XncgZ+raxoGMb1zkrBmt4ZPCCgaP/4S3TcTcyocEOXajPsAbNm3Zun5QyATcXWlevy4DIY/Q4nEwZaNrCYuJBONeKgLae1vTqP26CSnKy6qkwLVZak6u3lGfLuEuDfXT0AqaQ2DVpr5x4A+KAN+W+9++EdrwUhRYWYRkSRj1JN61xhRx0lxu+i2NGE2XKfCQPUlfFWj0cU8SNVvwJgL8bFi0WtwB0V3i2IZe7OfsfYBFRazhAW1fyweA9CemXvs7u5hWxPN4si1E/gQ8TeKjQn04Lq4/Edgn4IwhWDRXcLwG+AT2StcAtEui10tokp3GYW3wK5VL7yxCaGq+ZfPZdBrIs7cMxAuJTmPVlWQEjlaZcRD2x0oFQYyah2RI8WxvOGdaWUjz8hT5EbwE8ypenr2CE095eVX4BSqhzXsjLFOlm448soRhuOXeHW5hpF2dwTCdMpCKh752PhSd5JWo5TVLTwf7PuTedbRBVBJ9EW+FkFeR9sakGlleNKUvtoReC8seqFOEtmTiQGthwMahH4xbcyt1XnFjzQv/uEfqV2WOjiRs8qdV7tN/aFOwSPt0gIcdqRw30ghkvLIly0QhtvuDuTMSmCCobvoTe30iAhqEi5RtUhM+/tq3a0WcgJUrFBPVGeiI7s3hCOzWcn4Lo9KSllvxXzG5o5BrDK9vnRePcjrzulekBH50/6A8xQMVqu+0Hv2HXznuKb1XTPP9y893fWb0zupRf6c4kB6p906wwJXyCeMEKeFJxeY2B9COIJmqpwC63isUS14zY3RX9JoH1Y4QBwiftIGgOBXrwFFU3kKELEgCZYVuHRwUGrqC2xqhaDP2m0s/27M5oYuzY0YF05VbfdprzawAqUPqJugOH5BdvpQvSqM1bEhkIeC6Fv9ch0RoilRovujGnMgd7SuWq/pnllV2xMl9AP5R8PQvkpRDM/TTJGU02I3fw==
  template:
    metadata:
      name: harbor-credentials
      namespace: dev-tekton
