apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
data:
  buildkitd.toml: |
    debug = true

    # Allow HTTP registries (internal Harbor core service)
    [registry."harbor-core.default.svc.cluster.local"]
      http = true
