apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clusters-zjusct-io-cert
  namespace: cert-manager
spec:
  secretName: clusters-zjusct-io-cert
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "openng"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "openng"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "clusters.zjusct.io"
  - "*.clusters.zjusct.io"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s-zjusct-io-cert
  namespace: cert-manager
spec:
  secretName: s-zjusct-io-cert
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "openng"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "openng"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "s.zjusct.io"
  - "*.s.zjusct.io"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clusters-zju-edu-cn-cert
  namespace: cert-manager
spec:
  secretName: clusters-zju-edu-cn-cert
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "openng"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "openng"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "clusters.zju.edu.cn"
