---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBo+6Z+yisFw+2ve0k/AwBxinkKOFdrXEg/WCzNruuCX7L0SDK6ljGvrkQFEx8Npoxg6f4EnH4elMQ6E4sWep8Ui+Hu4I6klN7IQ13XVw0a+13/y2dy9NN5RX7FwHJQ8qs+bZZmGxx/JfTGDp7TiyFoK/TPQ3dLWY0s5v0yrg1Tf7hxdD6yvbo1yY+5j1BI4KtCUHJ9HVBt7aETheoMLgXWFwlwO54s0GwuTVMOxbIqbguT+6100Gt+28jrQC4q5FUeJ83qzPioazNEHpLOd0Wqj71m9D9R0caDZS+co+k6XoYhxo9TWPo2qYP30pv87G/GL6D8ULuPvciloQYhm2/lx8daOhrfLF9fLZ8sqd5AN2Q9Vmx7eM0nnhBLGjlyP86HePCUy24ZgcrxWr6Ne6ysZnvsLKaLzs+xTtYXRoKSS2LEYVrRskpVnjvguwjPMyvoqCZy97pUwrouwmbaYRQBhGnmUBH5Vwu+LkSiehLQ/M/EIzovF4aGGIFY3P9k8C9laatAODEC2xC7Q6cqvUHklX2abXVO9D5w5Z44F9g28Zpc2lu4hLPSsQ6gOl4Jh1jfuLSzVL4InqQIoIiek4dUecFh1y5LL+IyguU2dUYZs61lyRDGrz5kr7yZ3YzaADCK2ljLABwuiDtnKqPqjEa/58hi+hGinPRkzGyoMu8+NQigZstx0EAH3MaNjWlDy30PmCIZWRdmX2us3XP9Q1aqtfvUL/+E6jYlZzceA2J7Fp0M8duYoJe0
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
