[Unit]
# Fix SSSD and docker.socket circular dependency
# Without this, docker.socket depends on sssd.service which depends on docker.socket
DefaultDependencies=no
After=network.target
Before=docker.service autofs.service
