---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: new-api-secrets
  namespace: new-api
spec:
  encryptedData:
    postgres-password: AgB1qY/Cgg+PnYCgVinJ9m27AtVlBPWFz/ko9vfO38KHb6nA19YqFj+pqvuMgqzAaB0Rs4CfZB+TOh7/AEVehpzoWIVqJWR1GqaVha7cz4o33FZw25dgkEWG/JCJak7bkFNEOx6+J2ZPC0GlgyB2D7MTSM+6nS0pM1KiCDTmo3iyNFFY/qSHmPBIqR+PulnhIQuOpmoOs8V/WrBzg8DdO5yghn0qVaPdAO3yekhaCSty3ak7oBaMUwBJC0r2z9xmPM2YXaPMIU/FrW+3ioOvHfUqM9Gyjuzy0Cnc65Q67NKuDlulxq6dzoGX6anv5kgY2ecErizN2M9EI92scHiTrygm46TmF99wT9g+w9tMzwkABecA/sH7+oixpe09mjF+OZhk7FtfbjRkHUsFc7Qs0h2n15JQDiPEx2IBrD+acRteX70ZqvnZn2sEJ6HLadSkyiI5HJWSKACNgZwiOH9QCCE4VcdBnHGdCWUBPmP7LMN47RfWEN2BI75A1RGK9CFsR2jDVwy0qA2Wu4xXDhAogj6hJzsSjQ2ayXo37F5y2qBEZ7Ag0pWCW39CmnWSzTmGuFKP4ZA7GIbrwfFna2trpBrCxvNxniaBv0UiwovwNtEo/FBVS2DM+2lITpt6xq9lGR9RgRT9+2yUMUhUdO35B6k7A1IdbypSjPHZE9eYlXKR7KbZzJe8I06Hhk993+VXkqucF0WQI9jCyghsmPQXpA==
    redis-password: AgCIdTnOgj3hI92xs5LCNES65uSVG1YuKK2NElG0Q7QWYInJv5wh7exu8w6t7qIKBZIh6Qk9Rfi5rVxHUxPPQOXRhtmt0B39r80FVd6J6mVuYsorYlH1gvAmqBTgTgqPvzUU/uYfRatvyAA6OwMGOj3rRNlEBOLpi4hjtfL84EKjpE05KnwTtZQn8+zNGWQ4zks+jv7Wesy6/1Dgir3/xupIxYio/iIsBupkxocEA7GA0YTfHzI2WK1nFhvokb2Az6H72+savyI+j1QFVKevw9qMlb9MeWEQs/e98idAxmk0aWRut0565h+sPkqi1H+S6W9X1wLrYGBsMzfvIhC2MJ4yg4fi6xD9Umrvq5rAWhysJmcAGvOpUGfuFBtADlJ4avxSRU9Fk6E0SxDd4XQmU84JYfAtBwFHrIerTV5ie+9YdiY1bWZqe1AiFT1kcI36KvvOoA6bou2v4cNfRQjZP1XiWsBxagfRTAFWoFb2DmbVsjYySIenuXiuHYn8vyq1ZpEy0H0MElpgOwHtlEIX9kylxYpRZgO7N1m9un+usPDKT8QhDZQXj0LM5qW+8EZoxAfFSrwKIYFWk3cOSfVDyDfffZ9Xc5W5oCMJgTfUXeZIf0PkZ45ZMijLcX/Kis6KGUpyzcl8uHWLjfaecpVNNmnfDydne8hLBcrgt8PIgVCdrUvMejOqwyMYQaaey6ZUzulgbVKgxfeXFGrcjttixw==
  template:
    metadata:
      name: new-api-secrets
      namespace: new-api
