---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bmc-credential
  namespace: metal3
spec:
  encryptedData:
    password: AgCWcJOzGixAzYS0P2ELAScARiE+xdpIl6pJRWmqAjOxwWNolfnlyrUvm1k/CFj3GByNmkIfww2c3aolUQNHpa1D0F52mxFzmo0GRcEzTf8ll2F5mYBBWqJApXz6pwhFAiDEUgOQeD0oGtsTVDgT5M3Nl+8HjKcXbLGPT3bRFmCfDeNvU2CINiQfpEhXsvC9t6GAhaD0sYwtt4IWWFWtXffhSGR2Du6Sn+ftRcWDfrGoWogLq0QvLEklA8YKd1LMK5QEGCDXwhi0GxItbUQceTdieirXH920+Mkn5ilYmzVu7s//q1EQFIyrwtaxkaPDIRDiytu+Sh5/78KWSudlFXwuRx+wzAlScqoZu1UUewJ8mmptTzpikPB4ApXsuS9W2dYaROasB0rxIlA6CKQqvUF5kt2bwSDnd2gFwrnOpN9zrIchuzKTXoamqNpC6VbELJ5u8MeowQtTCGXegK6H+RZG7U2GOIdALP34DgLg1ETAqMErfNqAo+9NIFDVqykv/zBytJcEtY2/kyBoA4hthrad+4OWwb4weVYXP6pAE2q4+s+T8E0Q3T7qwhXIgza/4aSFKdVrcxAyIIdACfMm8JKhkP1tg6cY1b5MuYbA66mkAPy1Buk+9vrNvgZQ/8FlzL5chKJa1BmwIfZJHz0dzUc5e1KvPVIP0ORgDT8RuF1JQvPskbYoZn4GVgmQ8IzpBLvpjWetEZaTJiEu4zFyRQ==
    username: AgBeCU4g8HDb4MvtOd+kSAZuEBnKUDLxJklXf6K9BiV9NCXxO6QQnyoE+gL40gRn8iK2kdsA0NSZCcvbeIOGA4UF2Q8kft0nXZPvgXZZoTnzEXy06+sK9AqzrKes8LlCjP+zGsh5uRW5Xl9LIRasT1Y53MR+KmeS1xO/oIpSXBlYLgPDApJMSQKaXfPTSs2vWT5rTG7RQt9hGmoCiFEJM8CdeJ/ktCf4YjaBXK3DGKuQSWQYbxpIpn/09ore/fmqpin4eC4r6l9oc6fKiyrO3nZ50NLfYqT5PaJ9khU5tV/T/v7WRtWWzp2u3Mlg+sWW72pe8i5H8G881F0WePYbpmo75Bp/eiVtLBU4ZNDOLR7dmJyZbiKmKxrS5nESZFwOV9eNUBKJEP4iShx6JVvayy+2KICGeffRH4SqM+c/KspL+YJSEHaWNF7H35BvFa/nydabmrJWnX8R5+8hZyM9Dt8TkmGBQ6E8fi6Ic5e1BbtarqkMda1Y+qWdqtFQlrPUvg1N01Wr9i40NXiPraXO+FQeFwjC7WOgyg0QmwpJos3E6PaJsdynAxEmbWws/aWaxc9VhBJ7XqsMA4tuU9AzygCCPahXNOO73VYQZ3917avq2Qyy9ngZoB9yD1YYoTxjc7fczQ9ZsGId5FKOiq3Fi56lBb6tWl0NuWzjQGOhSimRbh67i81+18VCXoTkPAZOJK2t1pn8d1k=
  template:
    metadata:
      name: bmc-credential
      namespace: metal3
    type: Opaque
