# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-openclaw

helmCharts:
  - name: openclaw
    repo: https://serhanekicii.github.io/openclaw-helm
    includeCRDs: true
    releaseName: dev-openclaw
    namespace: dev-openclaw
    valuesFile: values.yaml

resources:
  - openclaw-sealed-secret.yaml
  - namespace.yaml

patches:
  - target:
      kind: HTTPRoute
      name: dev-openclaw
    patch: |-
      - op: replace
        path: /apiVersion
        value: gateway.networking.k8s.io/v1
