{
 "title": "OpenTelemetry Collector Container Receiver",
 "description": "dockerstatsreceiver\nfilelogreceiver",
 "tags": [
  "docker",
  "podman",
  "otelcol",
  "prometheus"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cloud_region", "label": "Cloud Region", "query": { "query": "label_values(cloud_region)" } },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": {
     "query": "label_values({cloud_region=\"$cloud_region\"},host_name)"
    }
   },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {
     "query": "label_values({cloud_region=\"$cloud_region\", host_name=\"$host_name\"},container_name)"
    }
   },
   { "name": "content", "label": "Content" }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(container_name) (container_uptime_seconds{host_name=\"$host_name\", cloud_region=\"$cloud_region\"}))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(container_name) (container_uptime_seconds{host_name=\"$host_name\", cloud_region=\"$cloud_region\"}))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{host_name=\"$host_name\", cloud_region=\"$cloud_region\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_file_bytes{host_name=\"$host_name\", cloud_region=\"$cloud_region\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Block I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", operation=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}-read"
    },
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", operation=\"write\"}[$__rate_interval])) * -1",
     "legendFormat": "{{container_name}}-write"
    }
   ]
  },
  {
   "title": "Resource Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_uptime_seconds{host_name=\"$host_name\", cloud_region=\"$cloud_region\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{host_name=\"$host_name\", cloud_region=\"$cloud_region\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (container_memory_percent_ratio{host_name=\"$host_name\", cloud_region=\"$cloud_region\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (container_memory_file_bytes{host_name=\"$host_name\", cloud_region=\"$cloud_region\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", operation=\"write\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", operation=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "-- variables provided by prometheus:\n-- $cloud_region, $host_name, $container_name\n-- log volume\nSELECT toStartOfInterval(\n    Timestamp,\n    toIntervalMillisecond($__interval_ms * 6)\n  ) as timestamp,\n  countIf(\n    SeverityNumber >= 21\n    AND SeverityNumber <= 24\n  ) as fatal,\n  countIf(\n    SeverityNumber >= 17\n    AND SeverityNumber <= 20\n  ) as error,\n  countIf(\n    SeverityNumber >= 13\n    AND SeverityNumber <= 16\n  ) as warn,\n  countIf(\n    SeverityNumber >= 9\n    AND SeverityNumber <= 12\n  ) as info,\n  countIf(\n    SeverityNumber >= 5\n    AND SeverityNumber <= 8\n  ) as debug,\n  countIf(\n    SeverityNumber >= 1\n    AND SeverityNumber <= 4\n  ) as trace,\n  countIf(\n    SeverityNumber = 0\n    OR SeverityNumber >= 25\n  ) as unknown\nFROM default.otel_logs\nWHERE (\n    timestamp >= $__fromTime\n    AND timestamp <= $__toTime\n  )\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\n  AND (\n    '$host_name' = 'ALL'\n    OR ResourceAttributes ['host.name'] = '$host_name'\n  ) -- map key must exist\n  AND mapContains(ResourceAttributes, 'container.name')\n  AND (\n    '$container_name' = 'ALL'\n    OR ResourceAttributes ['container.name'] = '$container_name'\n  )\nGROUP BY timestamp\nORDER BY timestamp DESC;"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as \"timestamp\",\n  Body as \"body\",\n  SeverityText as \"level\",\n  SeverityNumber as \"level_number\",\n  mapConcat(LogAttributes, ResourceAttributes) as \"labels\",\n  TraceId as \"traceID\"\nFROM \"default\".\"otel_logs\"\nWHERE (\n    timestamp >= $__fromTime\n    AND timestamp <= $__toTime\n  )\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\n  AND (\n    '$host_name' = 'ALL'\n    OR ResourceAttributes ['host.name'] = '$host_name'\n  ) -- map key must exist\n  AND mapContains(ResourceAttributes, 'container.name')\n  AND (\n    '$container_name' = 'ALL'\n    OR ResourceAttributes ['container.name'] = '$container_name'\n  )\n  AND (body LIKE '%$content%')\nORDER BY timestamp DESC\nLIMIT 500;"
    }
   ]
  }
 ]
}