apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openng
  labels:
    app.kubernetes.io/name: openng
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openng
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openng
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: openng
          image: ghcr.io/zjusct/openng:latest
          imagePullPolicy: IfNotPresent
          args:
            - -config
            - /etc/netgate/config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/netgate/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: cert-clusters-zjusct-io
              mountPath: /etc/netgate/cert/clusters-zjusct-io.crt
              subPath: tls.crt
              readOnly: true
            - name: cert-clusters-zjusct-io
              mountPath: /etc/netgate/cert/clusters-zjusct-io.key
              subPath: tls.key
              readOnly: true
            - name: cert-clusters-zju-edu-cn
              mountPath: /etc/netgate/cert/clusters-zju-edu-cn.crt
              subPath: tls.crt
              readOnly: true
            - name: cert-clusters-zju-edu-cn
              mountPath: /etc/netgate/cert/clusters-zju-edu-cn.key
              subPath: tls.key
              readOnly: true
            - name: cert-s-zjusct-io
              mountPath: /etc/netgate/cert/s-zjusct-io.crt
              subPath: tls.crt
              readOnly: true
            - name: cert-s-zjusct-io
              mountPath: /etc/netgate/cert/s-zjusct-io.key
              subPath: tls.key
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
      volumes:
        - name: config
          secret:
            secretName: openng-config
        - name: cert-clusters-zjusct-io
          secret:
            secretName: clusters-zjusct-io-cert
        - name: cert-clusters-zju-edu-cn
          secret:
            secretName: clusters-zju-edu-cn-cert
        - name: cert-s-zjusct-io
          secret:
            secretName: s-zjusct-io-cert
