---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins
  namespace: jenkins
spec:
  encryptedData:
    jenkins-admin-password: AgCoQkzI74XTIfth0MSLp+l1IvRgdnM/pX1yYCWaRxqDNltvQ+pG+pyWx6cCS7MqUuqzKaI06BiQlXrdy8/KnuCGy+7/PzFRx0hgI2zXtgcH0S3NlKeVX6O+RE+9gl5pA3whrexhC0BEdowHWpvVC4GjlfKIb4x6JPV5yL6O4kNL+MM+CWNEodxdDZS88b8DM4EeUH+28giK2OaMR6OZKw7tgYvM6okPwbHYePoDFTCCz54asayW2GEXqxsEbEY1Y5UYVDzxSHBWV2gqzJRTNKwYjxRwvbvEnokQF0S2wg3WXDGs1gupvZ3JsZXN+ux9gal2ZZXKsj8rztpaRVCc7xXWIRw2lbnxIohKLUcwGAS9T9i9c/DNDB7vqBZeKbduaF3MaW4IV5q+QulRIi2eul8OQVbr78SCjXvhW2w1v2wPhTb34EsKhG9PA8cIjqzpcFH7aI+YyOzVtZYkxoT3YbxGWbYNxE0bCWyRHC51a48RJKTGy8apk2aSZAG9OBKd8SUecO5DdVSZ2iE1Mpvu295Up+d6Yj4tbUYy8lQ+YV/dAFg7RwZjYdjN3pr7h39ZKr9pjJ6QpoDmcLGifSuLEQoJckTCToUwcILINYUf32bOZ62iSZCg4bIPa0KOZMPd3zec+9Jcch7GDfGBGhlnkJDR5ELPs5S0+niy9CU4lM37AUfg1nQ6gJ5amKYgnYOBGXPhkxQVRyN9lEbJxAEKNGvd3IJVU3aV
  template:
    type: Opaque
    data:
      jenkins-admin-user: admin
