services:
  packer:
    build: .
    image: harbor.clusters.zjusct.io/library/packer
    environment:
      HTTP_PROXY: http://172.28.0.4:3128
      HTTPS_PROXY: http://172.28.0.4:3128
    volumes:
      - .:/workspace
      - /dev/kvm:/dev/kvm
      - packer_cache:/root/.cache/packer
    # Debug only port
    # ports:
    #   - "127.0.0.1:2222:2222" # SSH
    #   - "127.0.0.1:5900:5900" # VNC
    network_mode: host
    privileged: true
    working_dir: /workspace
  # module test container
  # test modules faster using docker(based on qemu user-mode) instead of qemu vm
  test:
    image: harbor.clusters.zjusct.io/docker.io/library/debian:trixie
    # image: harbor.clusters.zjusct.io/docker.io/library/ubuntu:20.04
    # image: harbor.clusters.zjusct.io/docker.io/library/ubuntu:24.04
    # image: harbor.clusters.zjusct.io/docker.io/library/fedora:43
    # image: harbor.clusters.zjusct.io/docker.io/library/archlinux:latest
    # image: harbor.clusters.zjusct.io/docker.io/library/rockylinux:9
    # platform: os[/arch[/variant]]
    platform: linux/amd64
    # platform: linux/arm64
    # platform: linux/riscv64
    environment:
      HTTP_PROXY: http://172.28.0.4:3128
      HTTPS_PROXY: http://172.28.0.4:3128
    volumes:
      - .:/workspace
    working_dir: /workspace

volumes:
  packer_cache:
