services:
  packer:
    build: .
    image: harbor.clusters.zjusct.io/library/packer
    environment:
      HTTP_PROXY: http://172.28.0.4:3128
      HTTPS_PROXY: http://172.28.0.4:3128
    volumes:
      - .:/workspace
      - /dev/kvm:/dev/kvm
      - packer_cache:/root/.cache/packer
    # Debug only port
    # ports:
    #   - "2222:2222" # SSH
    #   - "5900:5900" # VNC
    privileged: true
    working_dir: /workspace

volumes:
  packer_cache:
