# Debian
- name: debian-13-amd64
  arch: amd64
  # iso_url: https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/debian-13-generic-amd64.qcow2
  iso_checksum: file:https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/SHA512SUMS
  iso_url: download/debian-13-generic-amd64.qcow2
  modules:
    - 20-software-control-plane
    - 20-software-k8s
    - 20-software-otelcol
    - 30-driver-nvidia
    - 30-driver-doca
    - 31-toolkit-cuda
    - 70-domain
    - 70-mount-local
- name: debian-13-arm64
  arch: arm64
  # iso_url: https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/debian-13-generic-arm64.qcow2
  iso_checksum: file:https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/SHA512SUMS
  iso_url: download/debian-13-generic-arm64.qcow2
- name: debian-13-riscv64
  arch: riscv64
  # iso_url: https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/debian-13-generic-riscv64.qcow2
  iso_checksum: file:https://mirrors.cernet.edu.cn/debian-cdimage/cloud/trixie/latest/SHA512SUMS
  iso_url: download/debian-13-generic-riscv64.qcow2
# Ubuntu
- name: ubuntu-24.04-amd64
  arch: amd64
  # iso_url: https://mirrors.cernet.edu.cn/ubuntu-cloud-images/noble/current/noble-server-cloudimg-amd64.img
  iso_checksum: file:https://mirrors.cernet.edu.cn/ubuntu-cloud-images/noble/current/SHA256SUMS
  iso_url: download/noble-server-cloudimg-amd64.img
  modules:
    - 20-software-control-plane
    - 20-software-k8s
    - 20-software-otelcol
    - 30-driver-nvidia
    - 30-driver-doca
    - 31-toolkit-cuda
    - 70-domain
    - 70-mount-local
- name: ubuntu-24.04-arm64
  arch: arm64
  # iso_url: https://mirrors.cernet.edu.cn/ubuntu-cloud-images/noble/current/noble-server-cloudimg-arm64.img
  iso_checksum: file:https://mirrors.cernet.edu.cn/ubuntu-cloud-images/noble/current/SHA256SUMS
  iso_url: download/noble-server-cloudimg-arm64.img
- name: ubuntu-24.04-riscv64
  arch: riscv64
  # iso_url: https://mirrors.cernet.edu.cn/ubuntu-cloud-images/noble/current/noble-server-cloudimg-riscv64.img
  iso_checksum: file:https://mirrors.cernet.edu.cn/ubuntu-cloud-images/noble/current/SHA256SUMS
  iso_url: download/noble-server-cloudimg-riscv64.img
- name: ubuntu-20.04-amd64-ascend
  arch: amd64
  # iso_url: https://mirrors.cernet.edu.cn/ubuntu-cloud-images/focal/current/focal-server-cloudimg-amd64.img
  # iso_checksum: file:https://mirrors.cernet.edu.cn/ubuntu-cloud-images/focal/current/SHA256SUMS
  iso_url: download/focal-server-cloudimg-amd64.img
  iso_checksum: file:download/SHA256SUMS
# Fedora
- name: fedora-43-amd64
  arch: amd64
  # iso_url: https://mirrors.cernet.edu.cn/fedora/releases/43/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2
  iso_checksum: file:https://mirrors.cernet.edu.cn/fedora/releases/43/Cloud/x86_64/images/Fedora-Cloud-43-1.6-x86_64-CHECKSUM
  iso_url: download/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2
  modules:
    - 20-software-control-plane
    - 20-software-k8s
    - 20-software-otelcol
    - 30-driver-nvidia
    - 30-driver-doca
    - 31-toolkit-cuda
    - 70-domain
    - 70-mount-local
# # Arch Linux # Deprecated
# - name: archlinux-amd64
#   arch: amd64
#   # iso_url: https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
#   iso_checksum: file:https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2.SHA256
#   iso_url: download/Arch-Linux-x86_64-cloudimg.qcow2
# Rocky Linux
- name: rockylinux-9-amd64
  arch: amd64
  # iso_url: https://mirrors.cernet.edu.cn/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2
  iso_checksum: file:https://mirrors.cernet.edu.cn/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2.CHECKSUM
  iso_url: download/Rocky-9-GenericCloud.latest.x86_64.qcow2
