---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: otelcol-snmp-secret
  namespace: opentelemetry
spec:
  encryptedData:
    SNMP_AUTH_KEY: AgCtarTOVoLGIVwu5qb1sVstFiZPbFohog7R9KIJfsiRmWxjZnDTC862pcxmWDIvlrMax/iJRS2f+3jDbIcIOvVekoe3cpo7K5ASqgNPwdvITDzAKbi+TL47QSDUoIswB+E9Uf7X5IalBlOHMT2rH5B1RMcrIvXP6FfhK4MOQ6SDE4hKlywnfx1SzSwAeD+Ag3/J2GdFbWn/EiGsIcXzsgOXJ14cN1Fj7/INTNShvCbIee1Sksd4fDDQVsXBhcPBABWRTxvbfhGIV7idq1F2s4XMd/tmoUw6b4YDsPo1PfPdTCJ0+7UtzLnMaWH9fpIcsHiVJ7y5OpTwRYWYAdBDYL3HnhWT7hNs0Bio4jE+2+uVI4/BFbd+u2FdZc9ya0x0ZduDjrP2Fxh0B9dMIoEWEEY8f2vOuJzHLJxUK/bSgg/m+9JPfAmGZj+CDf/PWl9PMZ7uddeOzc0bj4HGGgcj0iSxbXLpDsKRvSbwfYJ9XbjIXdJF6eIblDF8+loKl3Xt1w9YNfgMNZiDx5uB9LMgy+m0nx6p0KFuNoN1IjAuaKBuSYWUkDVYwImjnTaYnXZfw4g8az1I1gW+5Ll2GSZXVdvicOyakPtvteBu61YudwxL4VV7G9OsVdJ6CPxLX/xsyAOXcaRpV1ppj5ppfPACdR3GhUSTlEeXBQyGm6yVqpzaylgiF2itSoIO5kCxSUZ0WVgp0qllCgqpdGg73zY=
    SNMP_PRIVATE_KEY: AgBACsmfEpHQ9Gf1v91O6HGndiQIYE1VIwIO7SSKBTOgHVtlmqDp3lOggMKTsEc8kFXG1JReGQ6Gqiw693r5izXrzum8bzy0yzA4fWycrXxtf8uNMQw2EdoG0rRy9j80T5pr7G/6emTNMEgUlR7ViV/ayxfRyMIq4z96JCu7yaeqrjieQ7MTnAQ9gHfAdXz71wyfa4aTemerT7jJlabl/lxCbx1viJMl+XJZqkhT5zUIn5t1ctl73LYtMaGxJoIQVkm3qKDyZ9tK54P1FV3c7N2qT13NyOa7rGkEO+KnO26uU3dNvpouwMK6SMASBu1rcy2E+sW13vbFIUH908JG1k9sMeQV9t1XvWscDgEi9gWr1p33yHVNX3PwSjdGHue/ipFQTKOVSd8mkFqFaBKfEPZdnaxb1IRiTHzAZ6D361lYvXproX+dHMRK0Vzy5fjYvJ5rtn7HSHqQ1NuZI+0lZDA6pBv2bYzmBgBpkWXlSIsKz7y3LsOm2+hFMBogtjIgP5dk6nCgbFrpQAyMBNDPSOrT4Vvkm4RkTd1CGI9/VhGp9exCfIl4wrBtC46kkaxCMcUzZl/FXquE/R8nuHYPkzaPDPXhXLKvrWgcfGlIk5zX4UP7WXmd7LxwrAdTQ6X5zfRUg7iw2xCXfRUuy/2DutNLdBQfjR0Rg1vMqGtI16siWmqti6qvIzPIa+o9nYhQ+SlE4HQaCm+7YQmCRwdKsQ==
  template:
    metadata:
      name: otelcol-snmp-secret
      namespace: opentelemetry
