---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: otel-collector-secrets
  namespace: opentelemetry
spec:
  encryptedData:
    SNMP_AUTH_KEY: AgBzAxTesAVjDRo/QlD4h+RaQUM5mmP35gqZhpg8jTi3KyD682F419ZSF3JCCKSuCd6TLuWkqNnIpB1t2DMzWk1SMk0HEUY3+6w3Na80ODd2SSGNThhi1xSCrCTAcvqO/1GMZJhypvw1ury0OHsVhorgHh+R0IrfAEuEtRG9xZa7wl3l+cxtkiRjkb9yanTQj8vjmePRe5ocaFfzMoSKGXxFj6Yi5NG4b8Bk+HDocmV7XSD7gUQASOuRk8RSj+paTzkU/jkJ3DNYUM8BONq88fxkYyC/ceUmbxcG/yG+PWFJPsXP/Rw2Z2mM+mGK+pO3B75vUnzNGsAsC/c3MelKwMIc6heBIpB9QncHcY5yR02P6GAUYC8X8cwm5u+VDMFlE3SGhZEixL0LrP+HJ80ymsMpk1p2fgHkyV8xlzmSpdE47HnzIHLsQDy/TVZiqdcsbyqiRvGHQIbK0iQ/g9FJFXWU0ELo8FbC8/dJiqdDEUM+OLXEVyQrrXmIulU4R8ltHTqzV2CAN1n2de5U9fOmwObMo0QoU9sROSyaAoxPY15v63aVyE+oWtG2mZivAyS0FXPfxSrXKX0WwkZHI41i3AvrTtBR065VCWTz72TuVCifILWmxWjwi0Wxh3tOBDDxNtdVLberwdX0yK6r6QNHuDtFxEp0Y/QKyHfaK2urK+Tu3B85A/EZtGJW6TFfqxTJpI1kQuQgSY5v5+0nvbg=
    SNMP_PRIVATE_KEY: AgAPOoy72HRm6Agl8GubNvZTgcnNiAqvfn2u/7SoCZecdUP6Z2+O7Xyc/fwSDdOFVvYl57xnfIuITVuBf2sK9NiwYdx1keN0hXxTOqm15k6vHphu8rwiqdiuwDo2+0AO1D+05Jy5jVjG19I67gOZb6xoGogcLImldL1TJw72lvoGhcLzpoHL5wDM3XrMXH97L/V3NyWApfLQiMti/IiObR0Ekw4OeJKi5lLPNHLfe/xeRzsVFv54o4b+CQlAbP5+COYFGzVTDUNpxGezKJPuLNoyyN+B7ng6VQiOcRRSw2ZF6ZStVGczn1CcbwOY/A+ao8/GYGSx1fCrzARBQfzBvqM8xCIsoC0vXIcmBvoJ6Fy7MnMRjhdlcY/DaGmyoeNa8LCRxC11mlLi27qxaxL1Nh4G5XNNpc9pCSJVkdg2lGByPQx3WzWEwL8ktmPhAv/mk0/VAOKbTJiUDlajgoYgcCZftHSZXgOwAtwI1l1lAfGMdEz17uAurmm4m2I5/19rfIeLVWkJREsZN1QOOFHSH8y4A/az9lpZeUbofBKc0j+/YhE5zlgB/mf5qNUpqwi3UOwM1eKEgQY8svp5QXozV0kOahnJ09p0mrook8kmbSeld+dpKObwuIei5xoEOLxW85BH4wqhlcVVNv4dowdmvHFGH5eW65ht6AYosiWs/Wo6qpdeWPFI6oqlAFH53g1yj0tu27XwzDrDcgXnbHFwxA==
  template:
    metadata:
      name: otel-collector-secrets
      namespace: opentelemetry
