# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

global:
  domain: "argo-cd.clusters.zjusct.io"
  image:
    repository: harbor.clusters.zjusct.io/quay.io/argoproj/argocd

configs:
  cm:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/web_based_terminal/
    # enable kubectl exec in web UI
    exec.enabled: true
    # https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#kustomizing-helm-charts
    # https://github.com/kubernetes-sigs/kustomize/issues/4658#issuecomment-1815675157
    # enable helm and helm values override for kustomize in argo
    kustomize.buildOptions: "--enable-helm --load-restrictor=LoadRestrictionsNone"

  params:
    # https://github.com/argoproj/argo-cd/issues/13578
    # fixes HTTP reverse proxy 307 problem
    server.insecure: "true"
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/
    # allow applications and applicationsets in any namespace
    application.namespaces: "*"
    applicationsetcontroller.namespaces: "*"
    applicationsetcontroller.enable.scm.providers: false

  secret:
    # argocdServerAdminPassword: <sealed>
    createSecret: false

  # repositories:
  #   argo-private:
  #     type: git
  #     url: https://git.zju.edu.cn/zjusct/ops/argo.clusters.zjusct.io.git
  #     name: argo-private
  #     password: <sealed>
  #     username: not-used

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  replicas: 2
  httproute:
    enabled: true
    parentRefs:
      - name: envoy-gateway
        namespace: default
        group: gateway.networking.k8s.io
        kind: Gateway
    hostnames:
      - argo-cd.s.zjusct.io
      - argo-cd.clusters.zjusct.io

repoServer:
  replicas: 2

applicationSet:
  replicas: 2
