---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgBGy0M2kU8YTKOltsErM1ksJ7mgVl/d6572gSo/9CYFr9AGFFt4spRMYs9K++7Hp5bdytvQt0fdumZL/rWa1+RQOMpXX9A/hlvwrQxjRhRQd4gdk0YW6m+3C8i2zUSXV8a4CXQ/ZKb+g7xmGYBjE5jq/xpOtWi9a/dSFyWZkl2GYeol332sS4yESA9QrrlaxkByzfWmNbg6SQAxiETY6V6+l12qqPeLJlSmSJuTsoqlI0sNxi3DXk4mjdvcGTNx07cBTPjCp76fugUAx0V8NEkdx6YT0uwk0+8pgNi6nVtUWBrbSGfrSX+PyZ1xAXO/OY7BTtW+g7iYYquEZscuZUJ6Scyt/RgJPMABrceZ1cMyVK4/BrM3YhOsWsPI88UO/yL8s0yMogtwfZI1wIgoo+u0VEhfUMotV2KjzHLyTyQuSCgfMWGw3fS5cvaJqTA2+xmmVKVkG0anx4DRQ8skcYE3hpJ9dW1l0pjJ28xaHEojTsBaxLQUZIdp9pZVDe0oueFKeYHAuAj9dMJN17gSlWjJp5cZPuCtytomJBJmLHBen2qJcl0L4qqTDp/4rlA3mPl/sbT5YdgURQQRwUeBVyfps4rMoEA2gzKqnWVmBcuDvpBRcaWSO9QVsCrbpGMSzwqvUxUrq960AkmTHvVjwst9cHbxOJ8b4jwzVypI4xgUfFmT9N5Av7PqsB6CDcXawXRHORO8WRCdz6vwDeU=
  template:
    metadata:
      name: harbor-admin-password
      namespace: harbor
