apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trafficserver-cache
  namespace: trafficserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 256Gi
