apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sub2api

resources:
  - resources/namespace.yaml
  - resources/sealedsecret.yaml
  - resources/deployment.yaml
  - resources/httproute.yaml

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: "15.5.38"
    releaseName: sub2api-postgresql
    namespace: sub2api
    valuesFile: values/postgresql-15.5.38.yaml
    includeCRDs: true
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: "25.4.1"
    releaseName: sub2api-redis
    namespace: sub2api
    valuesFile: values/redis-25.4.1.yaml
    includeCRDs: true

transformers:
  - ../../image-prefix.yaml
