---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgCVTKa+wO+k+FhxC9++WaA/MLtncbd3/UlzbGNTt0O9AqDXCJYlPN8/ghjdLcFnHB1s08ffvOfjb3nVUAXnzQc8swUM9NYOdXplOi74KsJH9BDBmxrcLVbkRO3B8vZPe+BmM3SCXF3TRYywTmbIVLnzvJGNp3dT4xeuDf2f4D9K0RkGJpKp65/bu5+vHBcrymzCbhQsxdpHC7gcgTa34qKjz+DzlXcCcQZc97W9HgEF4bZuOBOCprz/PM/6sI+tzKF1U3pSoZR5AXY2CkTK1rrzkQrckivvokNkmPJQJmUFbWfeuMM3wydq+X/E2uZkFxC5uyFDDb8j/4PAl8LZvZtSjl03ENWhOfqhSnBlgI4aMW3Cha8ObA99XdHmhVj00T7UajWOfIP9S2ioJMV4G9y0gJOxzKNICotm4Knw9jArEtUzJKmjlYNUFACp9ljUt5L+vRw/SxljuR3tPvTpRD8TZeUkwmSV3337IZ7x31oIyz3zOiTgT8XEKTMpSkZy+DH4ULth2fLB+6157ZI+sM8s5yfZtwIhQ2ZE2qbPbuk7dPBx7dXxO1XLZ0onSNkAIqKZczWvhCSkhgYmwn9VTGcZzd3yM005sLKM+qb1Xq8uxuopeqMlPNWvfjOmUv5vrqQXD/PFwq8A4BK2z2d21fthlEUHSeAMmZp0nBGIkODjGivrg/J/5UGczGNL4sRFyfprpCIe79TB1FnPTyi7Fkp01FA22Po/eZOO85YnR6A9FWZNSTgAAuAohLxnxxeN5Ztz7FjUgFA55JLcF99TlKrc/58=
  template:
    metadata:
      name: gitlab-runner
      namespace: gitlab
