---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  encryptedData:
    runner-token: AgCXy61SqpJXkkfZl1Ad0Ps+DdqFWmSWAul57e2yCCbboQ1tkTQRU3TUNZB+ygk/pojbE7u0mQAN8+X8h8EBLfSjrWzfVErIylJYMSXs0IThpAAfPAsIUVBunGP9U2Wlj00e4zrxD/RxNKwixi8EPD5O0DGsrm9Fp5ImWM42qtli0nqyBz/C8rnBWfvpi6O4LoUj2hov8wVRW1uRXQsrDvr4pHu/1uAz39As6bus1R+0KbE/RBWohCkndTHq67mTywlzyFoqPaLOESqS0H1qfhRepCdOrjie9o/g9/c+6F/vxaWh5Rb/UdlVjL7xCgvhiZ5cSLCjEiINM1XKBhIkaZ+HlZIDxewzhI4nATjj4ccJSWK8seeFZtNUiG+qEo7jvWYc+MH3Wjol2XZYvchS140rnOJSlLqQAhcqf4VTyB2aFdq0mMXdzyybphjIP5e4Nlo0eenFe3iGESxdMC/7JeL5kB5jllAzfk38O0ieWAbu0xD6HIxAbGiRSfvZ72vhFfLwGTdV+xnbY3LtqaERidOo0rcvxO28fmBSi4jotzl3Hm6RDJGCqW8YskfSBznD+fBrz3rL7n4S5735oxut8ZaPKdQQHYe2kbh9bqcKV5mF15/myDgy3rf3PwK3W5U3yB8GjEnDI2xuLCyZLlOPig9EJt9LaCYLMAtZRPYoAeBgmdzB3W8V3DKIGzT4K1s/Nza+9KEy1kuNBssj/7+GK/eXx9j4QNn3lP3CQyM9P6rGz00h+Z4N/ncY0FrqYFrCEBsJDsxaqIMTmQIUHhrdgWF6WN4=
  template:
    metadata:
      name: gitlab-runner
      namespace: gitlab
