---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgBmDjzMwGHuze9UMOAiFPDwzL2Gl7WLv8WINuMWI3yS/mQD8ozH760Mdx+WWYd9KOdjTptONtsdjtAiwy1kPydxMmi0GOftIUFWLGjHCOJT5IjES+ttkOz5ToR3TKHhkLFU5XPj8FXSVoBZU3Ol4VCqn9qVkUJ+VnH++FBhS6DWQKeuUWOdm6Px5TwPsczOftg6V6Ai9vXt89ejH0RpxgsChB7mM1jx8462mAzQ5PbHBgSQdWojROFBcr7uzcJZJIyPfObhWGCi2Mm2qqTWKBfl23bijbAgbMYl39i4HiB9Q8oRl2SUq1OK4CS1qdOfPLLN70R7Ai1xEPc1jpYrd7cAhUYONhWFi4XatVbJnaIDUMojTmVsAK0EjF3QYn8fppM+DxKpZxmARuBh1T39c/YX4mAVwGRdqOmxA1DdX6pV/29LhVIlC5gAUoMOErp7GfuNQgNLoySXjeqctdrZMwmDMv0D/24t5xC+SqDnThhC5ixUgKgApSA/+Cec4vMBuQeGXZeS7Xq6qvd7mQrpdv7m1GUE+qfSeTGgmISLOWPNuMoH3fVUoSmku+3VdnAV6Cf4jVDvaU8eF2foPsSvyv2XvoBGHEtPdb61aY4qBL5WWYc8dHyXYYuT8c6RfR94eJFskAK5idoJLSU/EsD8aWEa2vJ/gwpnshaIDRRCBF2JjoDuEZxTS7T3OPAd1/XhyVg=
    runner-token: AgAAIFkWismTylZ2p2gl2SU9cjOUMjDJEpHPz4C5QNCTs8+th4TLLZCwubrL9CBDBsshlnazzeNMRRYu8jEyYAjV0Aj0kaK2iQteLgS8vIBtyeyxRU7htVSCoZA994moxxM4B7z5hZs2Ag0ip/9dob0uTOUTmhlicSvI0S0ArXnGrN4wNQBJiSD4n183P3rjRJuNWWZ33KJ5Y2DXbrQLjWCtj/xSpRlXXSgkl3JUrZJXYT4vZw6q3Uirn/AwjWSOmFoyjRZbHuX5EySVehQgh6Yj8GpRvsAkSDMroicxZqbYsuLSrMws1jBBwDX/IwbwmYePSpwsRCMtUqcPYCbzJ+gAFUGxv+dOfmBg7V6ICYFFCoQdmjltNuAfvHcbY0yNvh8eZwyfFlZr9/mH2VFP/bpDiblo/w+qbY/2U4uCD+G4C4a7/qAA1EkfqFKuukgOMn8VXt4SI5FDDXsS0fU1pfqy8ZavZSxP+pyGyjDOruOriR6uVm47R+sfcUGXPtikq9XhxAOSXPYfO2g69O6yhefqEOHm4KjEmDE0qrEs2Lf3ihx0p4cYzQwyJgG4p4deTer9xlu3Mk9xEp3oQXVU+XkhJShaxvei9o6XqqQPzRUt4F9Avd1tt62Hg+Zz4Yi8B2hfOQibhof5AXnZEK0DZxe39B4POzp70b/nEnLU/KE3UvmERa1A2QimkRUVx2NqdRgv/7YoHDL2WpNUBVXOKvUDLIK+QJRKbu29RaAh+7zG8HEv9HyZcYMKhAC3Ar6GwfuEDpLiy/33pRRsXSeC3LiPWvY=
  template:
    metadata:
      name: gitlab-runner
      namespace: gitlab
