apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm
resources:
- resources/namespace.yaml
- resources/httproute.yaml
- resources/sealedsecret-masterkey.yaml
- resources/sealedsecret-api-keys.yaml
- resources/configmap-api-debug-env.yaml
- resources/configmap-claude-code-session-hook.yaml

helmCharts:
- name: litellm-helm
  repo: oci://docker.litellm.ai/berriai
  version: 1.83.14-stable
  releaseName: litellm
  namespace: litellm
  includeCRDs: true
  valuesFile: values/litellm-helm-1.83.14-stable.yaml

patches:
  - target:
      kind: Deployment
      name: litellm
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DATABASE_URL
          value: postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_NAME)

transformers:
  - ../../image-prefix.yaml
