apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-ceph-dashboard1
  namespace: observation
  labels:
    grafana_datasource: "1"  # 这是一个“暗号”，Sidecar 看到这个标签才会自动加载它
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Dashboard1
      type: prometheus
      access: proxy
      url: http://prometheus-stack-kube-prom-prometheus.prometheus.svc.cluster.local:9090
      isDefault: false
      jsonData:
        tlsSkipVerify: true
