---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gzctf.fullname" . }}
  labels:
    {{- include "gzctf.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.gzctf.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gzctf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "gzctf.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gzctf.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gzctf
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.gzctf.image.repository }}:{{ .Values.gzctf.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gzctf.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.gzctf.service.httpPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.gzctf.service.metricsPort }}
              protocol: TCP
          {{- with .Values.gzctf.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.gzctf.persistence.enabled }}
            - name: gzctf-files
              mountPath: /app/files
            {{- end }}
            - name: gzctf-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          {{- with .Values.gzctf.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.gzctf.persistence.enabled }}
        - name: gzctf-files
          persistentVolumeClaim:
            claimName: {{ include "gzctf.fullname" . }}-files
        {{- end }}
        - name: gzctf-config
          configMap:
            name: {{ include "gzctf.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gzctf.postgresql.fullname" . }}
  labels:
    {{- include "gzctf.postgresql.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gzctf.postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gzctf.postgresql.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.gzctf.config.database.password | quote }}
          {{- if .Values.postgresql.persistence.enabled }}
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/
          {{- end }}
          {{- with .Values.postgresql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.postgresql.persistence.enabled }}
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: {{ include "gzctf.fullname" . }}-db
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
---
{{- if .Values.garnet.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gzctf.garnet.fullname" . }}
  labels:
    {{- include "gzctf.garnet.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gzctf.garnet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gzctf.garnet.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: garnet
          image: "{{ .Values.garnet.image.repository }}:{{ .Values.garnet.image.tag }}"
          imagePullPolicy: {{ .Values.garnet.image.pullPolicy }}
          ports:
            - name: garnet
              containerPort: {{ .Values.garnet.service.port }}
              protocol: TCP
          {{- with .Values.garnet.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
