#!/usr/bin/env python3
"""Check for plaintext secrets in YAML files.

Pre-commit integration:
- Accepts file list as arguments (when pass_filenames=true)
- Checks only YAML files changed in production/dev directories
- Allows safe secret types: kubernetes.io/service-account-token (auto-generated)
- Rejects: Opaque, kubernetes.io/tls, and other custom secret types

Usage:
  scripts/check-secrets.sh [--fix] [files...]

With --fix: attempt to auto-seal plaintext secrets using kubeseal
Without files: checks all YAML files in production/dev directories
"""

import os
import sys
import yaml
import argparse
from pathlib import Path
import subprocess

try:
    import yaml
except ImportError:
    print("Error: PyYAML not installed. Install with: pip install pyyaml")
    sys.exit(1)


class SecretChecker:
    """Check for plaintext secrets in GitOps YAML files."""

    # Secret types that are safe to commit (auto-generated, non-sensitive)
    SAFE_SECRET_TYPES = {
        'kubernetes.io/service-account-token',  # Auto-generated by K8s
    }

    def __init__(self, auto_fix: bool = False):
        self.auto_fix = auto_fix
        self.errors: list = []
        self.fixes: list = []

    def run_command(self, cmd: list, timeout: int = 30) -> tuple:
        """Run shell command. Returns (returncode, stdout, stderr)."""
        try:
            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=timeout, check=False
            )
            return result.returncode, result.stdout, result.stderr
        except subprocess.TimeoutExpired:
            return 1, "", f"Command timeout after {timeout}s"
        except FileNotFoundError:
            return 1, "", f"Command not found: {cmd[0]}"

    def seal_secret(self, filepath: Path) -> bool:
        """Auto-seal a plaintext secret using kubeseal. Returns True if successful."""
        if not self.auto_fix:
            return False

        sealed_filepath = Path(str(filepath).replace('.yaml', '-sealedsecret.yaml'))

        # Create the sealed secret
        code, _, stderr = self.run_command([
            'kubeseal',
            '-f', str(filepath),
            '-w', str(sealed_filepath)
        ])

        if code != 0:
            print(f"    [WARN] Failed to seal {filepath}: {stderr}")
            return False

        # Validate
        code, _, stderr = self.run_command(['kubeseal', '--validate', '-f', str(sealed_filepath)])
        if code != 0:
            print(f"    [WARN] Sealed secret validation failed: {stderr}")
            return False

        self.fixes.append(f"  {filepath} -> {sealed_filepath}")
        return True

    def check_file(self, filepath: Path, repo_root: Path) -> bool:
        """Check a single YAML file. Returns True if passed."""
        # Skip sealed secrets
        if 'sealedsecret' in filepath.name.lower():
            return True

        # Skip chart templates
        if '/charts/' in str(filepath):
            return True

        rel_path = str(filepath.relative_to(repo_root))
        passed = True

        try:
            with open(filepath, 'r') as f:
                # Handle multi-document YAML files
                try:
                    docs = list(yaml.safe_load_all(f))
                except yaml.YAMLError as e:
                    self.errors.append(f"  {rel_path}: YAML parse error: {e}")
                    return False

                for doc_idx, doc in enumerate(docs):
                    if doc is None:
                        continue

                    if doc.get('kind') != 'Secret':
                        continue

                    name = doc.get('metadata', {}).get('name', 'unknown')
                    secret_type = doc.get('type', '')
                    namespace = doc.get('metadata', {}).get('namespace', '')

                    # Check if this is a safe secret type
                    if secret_type in self.SAFE_SECRET_TYPES:
                        continue

                    # Found a plaintext secret
                    passed = False
                    type_str = f" (type: {secret_type})" if secret_type else ""
                    ns_str = f" in namespace {namespace}" if namespace else ""
                    self.errors.append(
                        f"  {rel_path}: Plaintext secret '{name}'{ns_str}{type_str}"
                    )

                    # Try to auto-seal if enabled
                    if self.auto_fix and secret_type not in self.SAFE_SECRET_TYPES:
                        if self.seal_secret(filepath):
                            self.errors[-1] += " -> SEALED"

        except FileNotFoundError:
            self.errors.append(f"  {rel_path}: File not found")
            passed = False
        except Exception as e:
            self.errors.append(f"  {rel_path}: Error: {e}")
            passed = False

        return passed

    def get_files_to_check(self, files: list, repo_root: Path) -> list:
        """Get list of YAML files to check.

        If files are provided (from pre-commit), use them.
        Otherwise, find all YAML files in production/dev.
        """
        if files:
            # Filter to only YAML files in production/dev
            yaml_files = []
            for f in files:
                filepath = Path(f)
                if not filepath.is_absolute():
                    filepath = repo_root / filepath

                if filepath.is_file() and filepath.suffix in {'.yaml', '.yml'}:
                    # Only include files in production or dev
                    rel_path = str(filepath.relative_to(repo_root))
                    if rel_path.startswith(('production/', 'dev/')):
                        yaml_files.append(filepath)

            return sorted(yaml_files)
        else:
            # Find all YAML files in production/dev, excluding charts and sealed secrets
            yaml_files = []
            for env_dir in ['production', 'dev']:
                env_path = repo_root / env_dir
                if env_path.exists():
                    for yaml_file in env_path.rglob('*.yaml'):
                        if 'charts' in yaml_file.parts:
                            continue
                        if 'sealedsecret' in yaml_file.name:
                            continue
                        yaml_files.append(yaml_file)

            return sorted(yaml_files)

    def run(self, files: list = None) -> int:
        """Run security checks. Returns exit code (0=pass, 1=fail)."""
        repo_root = Path(__file__).parent.parent
        os.chdir(repo_root)

        files_to_check = self.get_files_to_check(files, repo_root)

        if not files_to_check:
            print("No YAML files to check")
            return 0

        print(f"Checking {len(files_to_check)} YAML files for plaintext secrets...")

        # Check each file
        all_passed = True
        for filepath in files_to_check:
            if not self.check_file(filepath, repo_root):
                all_passed = False

        # Print results
        print()
        if self.fixes:
            print("=" * 80)
            print("AUTO-SEALED:")
            for fix in self.fixes:
                print(fix)

        if self.errors:
            print("=" * 80)
            print("FAILED - Plaintext secrets found:")
            for error in self.errors:
                print(error)
            return 1
        else:
            print("=" * 80)
            print("PASSED - No plaintext secrets")
            return 0


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Check for plaintext secrets in YAML files (pre-commit integration)"
    )
    parser.add_argument(
        '--fix',
        action='store_true',
        help='Auto-seal plaintext secrets using kubeseal'
    )
    parser.add_argument(
        'files',
        nargs='*',
        help='YAML files to check (from pre-commit pass_filenames)'
    )
    args = parser.parse_args()

    checker = SecretChecker(auto_fix=args.fix)
    return checker.run(files=args.files)


if __name__ == '__main__':
    sys.exit(main())
