apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: dev-buildkitd
data:
  buildkitd.toml: |
    debug = true

    # Allow insecure (HTTP) registries
    [registry."harbor-core.default.svc.cluster.local"]
      http = true
      insecure = true
