apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: dev-buildkitd
data:
  buildkitd.toml: |
    debug = true

    # No insecure registry config needed for harbor.clusters.zjusct.io
    # It uses proper TLS certificates
