apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: dev-buildkitd
data:
  buildkitd.toml: |
    debug = true

    # Allow insecure (HTTP) registries
    [registry."harbor-registry.default.svc.cluster.local:5000"]
      http = true
      insecure = true
