# Patch to update buildkitd deployment to use cert-manager generated certificate keys
# cert-manager uses: ca.crt, tls.crt, tls.key
# buildkit expects: ca.pem, cert.pem, key.pem
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
spec:
  template:
    spec:
      containers:
        - name: buildkitd
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --tlscacert
            - /certs/ca.crt
            - --tlscert
            - /certs/tls.crt
            - --tlskey
            - /certs/tls.key
