---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overleaf-secret
  namespace: overleaf
spec:
  encryptedData:
    OVERLEAF_EMAIL_SMTP_PASS: AgAQKYfqPCwwLGWJ3HRtSTCLq6duMTSRoguZJiy8YU3e3WpoPflV3mMQ1QYFf5XOqR7TSWdEAwpzL2BiqaRwYxu4qMn5Q+EC/IzIkiEj1oO2j5/4G1cKZAAcQLEs/z2jIG++I1B6Eh/UfwYzTfCtWdQofP/3pJJJmqq5TsucaJxQ0SR56aiAgnz44MzAVTkXNh8KWrE1EsuO+JeYcSmfex/AAxadYqGsmQRXx8at07pH7dwiT0/OB8m+UtJKM2kXnAk9FfJBp2XzpxaWNrIV4Gsi8cHuoJgDgp7I75I1byJzJOG+OtiJKEZwh65EgeRVatRyxh/BYdF3dpR9NhS350U8JOEiwPtGOirXW7FDWo8cfFZ/KPdcZLIrrKnfNvZTTuEh3g8Y2pb2ZUiKE0RSBr3qnDowUcwxSH3c91eqCwxAJ7TO2MERf7lYT1Ag++OHbgFd8ACzRyah6H5ctKIVpXUliJh5fv6bCBtQF7aS1+EHU9nI66m/O2C3LU2y5JuJPUCGaxj9pgT1iK53JJ/LKhn0/zj34Osspm7GttdNcPQfuM8yAgqjIuiIBiTgQUgAtBBNC+mRVJEOJdBQW2YAhDjWvXssDiGT5xIwQB0i+OZC7VazRI+pqN133Nzz87xf0z4c8Sw6ML39XUGoc5zkumLSY0NN2j6wWxiDsPfrdRQy9mjPwJ2WW055uJ1B5IPZTcel1IIXg2CuNm/JEJ8=
    OVERLEAF_SESSION_SECRET: AgCUkmdi7wyh5qVJoo1bJII6vjBrAleC59MhwkEnj0+mNkkx3IHYt9RRkGo5cD8geZCLaq7e/jAKXTgx7GyPcXVPlHiEYh3M2ELcYJ/s97zNeDKgOvhhNoJUWcL3zZvXlHJG47ueZkyPn07ggkX4/lluMfGNUHKqB62ca8Q2zoyXvHuHVaM+w71diHY5Fu8YamkH4KCO9JFkpqDS0Oz+YsE/Iyjm+g84rBgTIn6/oMZbgwVCkaMXVsy9W5ozYjXIQE7EbYXuaRBRgvYoDa7sRO7cXvVwJso03cacvC0ayFCM8fJeYiZKdanIKmdA4KCqy+Uu8PEgIO4ddrdjBk+3+qE37Xnj71BPhQ2IBcW/x7NzbHkdT0zoDshvxC0Px8A6Dnuft/jp2rtDa0ygrgrTjSO44Ku+8Injof5riI43lED+/G1KRkt1b5hW9HvyHR5gTj4uFdpBdNbplQMSSFgiQBsT+R3wzbgbv/MqBo24f3mTCJZK28Y1lG6cbn+wrhK9x0lONaAy6F32OH3IfQ8qtbuKkcJLDrXgd8/eSe2mqzLShO7Odh0GHvXwbTxfj8HscYvMTXICIFOFMv5sHf4cQ0wJR4rU4IXR78kpJTzfTfmPHg3NRaVFdz16f7RB2WvAHy/eUKZ8T9l6sQ8NpY4mq11doyf6+nyFdVhcJ6idCac/0+1by2py57DSdHjibl+4GKtO+JM7vAs/hQ89xR4gDyMRz2DsxKlBeZ/heND5biKPJR8nBJ6R/fqRcbgIhe3IJn/nqzUehICFeaHWokjUZj8=
  template:
    metadata:
      name: overleaf-secret
      namespace: overleaf
    type: Opaque
