# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml

agent:
  image:
    registry: harbor.clusters.zjusct.io
    repository: hub.docker.com/jenkins/inbound-agent

controller:
  image:
    registry: harbor.clusters.zjusct.io
    repository: hub.docker.com/jenkins/jenkins

  sidecars:
    configAutoReload:
      image:
        registry: harbor.clusters.zjusct.io
        repository: hub.docker.com/kiwigrid/k8s-sidecar

  admin:
    createSecret: false
    existingSecret: jenkins
    # username: admin
    # password: #<sealed>

  additionalPlugins:
    # # following 4 plugins are included by default
    # - workflow-aggregator
    # - git
    # - kubernetes
    # - configuration-as-code
    - matrix-auth
    - github
    - gitlab-plugin
    - dark-theme
    - theme-manager
    - scmskip
    - s3

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: nginx
    hostName: "jenkins.clusters.zjusct.io"

  secondaryingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: nginx
    hostName: "jenkins.s.zjusct.io"
    paths:
      - "/"

  # existing secret "secret-credentials" and a key inside it named "github-username" should be used in JCasC as ${github-username}
  # we can use existing secret to avoid hardcoding sensitive data in JCasC yaml
  # existingSecret: jenkins-jcasc

  # notice: Helm Chart has already prepared a default config named jcasc-default-config.yaml
  # which is defined in template helpers: https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/_helpers.tpl
  # it contains kubernetes, urls and etc, so no need to configure it again
  JCasC:
    enabled: true
    overwriteConfigurration: true
    configScripts: {}
      # reference https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos
