# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml

agent:
  image:
    registry: harbor.clusters.zjusct.io
    repository: hub.docker.com/jenkins/inbound-agent

controller:
  image:
    registry: harbor.clusters.zjusct.io
    repository: hub.docker.com/jenkins/jenkins

  sidecars:
    configAutoReload:
      image:
        registry: harbor.clusters.zjusct.io
        repository: hub.docker.com/kiwigrid/k8s-sidecar

  admin:
    createSecret: false
    existingSecret: jenkins
    # username: admin
    # password: #<sealed>

  additionalPlugins:
    # # following 4 plugins are included by default
    # - workflow-aggregator
    # - git
    # - kubernetes
    # - configuration-as-code
    - matrix-auth
    - github
    - gitlab-plugin
    - dark-theme
    - theme-manager
    - scmskip
    - s3

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: nginx
    hostName: "jenkins.clusters.zjusct.io"

  secondaryingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: nginx
    hostName: "jenkins.s.zjusct.io"
    paths:
      - "/"

  existingSecret: jenkins-jcasc

  JCasC:
    enabled: true
    overwriteConfigurration: true
    configScripts:
      # reference https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos
      kubernetes: | # https://plugins.jenkins.io/kubernetes/
        jenkins:
          clouds:
            - kubernetes:
                containerCap: 10
                containerCapStr: "10"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                name: "kubernetes"
                namespace: "jenkins"
                podLabels:
                  - key: "jenkins/jenkins-jenkins-agent"
                    value: "true"
                serverUrl: "https://kubernetes.default"
      misc: |
        unclassified:
          location:
            url: "http://jenkins.clusters.zjusct.io/"
