# https://github.com/argoproj/argoproj-deployments/tree/master/argocd
apiVersion: v1
kind: Namespace
metadata:
  name: argo-cd
---
# https://argo-cd.readthedocs.io/en/stable/operator-manual/project-specification/
# https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#the-default-project
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#allowing-additional-namespaces-in-an-appproject
  # let argo deploy applications in any namespace
  sourceNamespaces:
    - '*'
---
# https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    repoURL: https://git.zju.edu.cn/zjusct/ops/argo.clusters.zjusct.io.git
    path: argo-cd
  destination:
    name: in-cluster
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#manage-argo-cd-using-argo-cd
      # must use ServerSideApply
      - ServerSideApply=true
