apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
resources:
- resources/namespace.yaml
- resources/config.yaml
helmCharts:
- name: metallb
  repo: https://metallb.github.io/metallb
  includeCRDs: true
  releaseName: metallb
  version: 0.15.3
  namespace: metallb
  valuesFile: values/metallb-0.15.3.yaml
transformers:
  - ../../image-prefix.yaml
