apiVersion: v1
kind: Service
metadata:
  name: trafficserver
  namespace: trafficserver
spec:
  type: LoadBalancer
  selector:
    app: trafficserver
  ports:
    - name: proxy
      port: 8080
      targetPort: proxy
