apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-mcp-server
resources:
  - resources/namespace.yaml
helmCharts:
  - name: kubernetes-mcp-server
    repo: oci://ghcr.io/containers/charts
    version: 0.1.0
    includeCRDs: true
    releaseName: kubernetes-mcp-server
    namespace: k8s-mcp-server
    valuesFile: values/kubernetes-mcp-server-0.1.0.yaml
transformers:
  - ../../image-prefix.yaml
