apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openlist-files
  labels:
    app: openlist
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
