apiVersion: v1
kind: Service
metadata:
  name: openlist
  labels:
    app: openlist
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5244
      protocol: TCP
      targetPort: 5244
  selector:
    app: openlist
