apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway
resources:
- resources/namespace.yaml
- resources/envoy-gateway.yaml
helmCharts:
- name: gateway-helm
  repo: oci://docker.io/envoyproxy/
  includeCRDs: true
  releaseName: envoy-gateway
  valuesFile: values/gateway-helm-1.7.0.yaml
  namespace: envoy-gateway
  version: 1.7.0
transformers:
  - ../../image-prefix.yaml
