apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: tekton-pipelines
type: Opaque
stringData:
  config.json: |
    {
      "auths": {
        "harbor.clusters.zjusct.io": {
          "auth": "REPLACE_WITH_BASE64_CREDENTIALS"
        }
      }
    }
